### ISSUE TITLE
STL not generate 3D shape? X Y Z and faces Triangele generated properly but STL not generated 3D? 

### ISSUE THREAD

**Issue by selvakarna** [WoLpH/numpy-stl#101]
STL not generate 3D shape? X Y Z and faces Triangele generated properly but STL not generated 3D? 
 
 X Y Z vectors not forming as 3D in STL, everything formed as single dimension ? 
 X Y Z points are from 300 dicom slides? its 3d Volume image?
but STL not forming as 3D ?

**Comment by Uvar** [comment]
I'm afraid it is tough to interpret your question; or distilling it from the string of question marks anyway.

The STL format is in essence just a point cloud.
If you want to visualize this, you can use tools like MatplotLib or import the STL into any 3D viewer supporting STL.

If your question is pertaining to the way the data is handled internally by the code, please help understanding by re-phrasing the question in a specific form.

**Comment by selvakarna** [comment]
i don't want need visualize STL? i am asking how to make STL from x y z co-ordinates ? the x y z co-ordinates are extracted from 3d volume image? can you give sample of this my question?
