### ISSUE TITLE
Create a STL file with XYZ 2D arrays

### ISSUE THREAD

**Issue by tomyferra** [WoLpH/numpy-stl#104]
I need help of how to create a STL file having my X Y Z 2D arrays.
I saw this example but i'm having trouble finding a way out. 
https://github.com/WoLpH/numpy-stl/issues/89

![image](https://user-images.githubusercontent.com/11900440/56966573-c390db80-6b35-11e9-9854-7227aefcc8c6.png)

This is the problem in my code, where 
xInterp, yInterp and zInterp are 2D arrays

Thank you!

**Comment by WoLpH** [comment]
This issue has been discussed over email a bit already but I'm not sure how to fully solve it. Here's the code for completeness though :)

```python
import numpy as np

x_all = np.hstack(valorX)
y_all = np.hstack(valorY)
z_all = np.hstack(valorZ)

tris = mtri.Triangulation(x_all, y_all)

data = np.zeros(len(tris.triangles), dtype=mesh.Mesh.dtype)
m = mesh.Mesh(data, remove_empty_areas=False)
m.x[:] = x_all[tris.triangles]
m.y[:] = y_all[tris.triangles]
m.z[:] = z_all[tris.triangles]
m.save('model.stl')

from matplotlib import pyplot
from mpl_toolkits import mplot3d

# Create a new plot
figure = pyplot.figure()
axes = mplot3d.Axes3D(figure)

# Render the cube
axes.add_collection3d(mplot3d.art3d.Poly3DCollection(m.vectors))

# Auto scale to the mesh size
scale = m.points.flatten(-1)
axes.auto_scale_xyz(scale, scale, scale)

# Show the plot to the screen
pyplot.show()
```
