### ISSUE TITLE
Typo in to_binary()

### ISSUE THREAD

**Issue by smgreenwood** [WoLpH/numpy-stl#106]
It looks like there is a typo here:
https://github.com/WoLpH/numpy-stl/blob/4c6f1ba65ebfbe4160a4d671a5b318bb825aa3dc/stl/main.py#L79

The line reads:  'Convert STL files to ASCII (text) format'

I believe ASCII should be changed to binary:  'Convert STL files to binary (text) format'

**Comment by WoLpH** [comment]
Indeed, a copy paste from the to ascii function and I forgot to change the docs
