### ISSUE TITLE
Wrong method used in rotation_matrix

### ISSUE THREAD

**Issue by Hepheir** [WoLpH/numpy-stl#107]
https://github.com/WoLpH/numpy-stl/blob/4327bf79b2a59885651aa1a4ffd658b50ffacdc8/stl/base.py#L433-L435

In my opinion, the method **`numpy.zeros((3,3))`** should be replaced with **`numpy.identity((3,3))`** @ line 435.

https://github.com/WoLpH/numpy-stl/blob/4327bf79b2a59885651aa1a4ffd658b50ffacdc8/stl/base.py#L491-L494

Zero matrix will cause of losing the original data when it is dot-producted, while indentity matrix will preserve it.

**Comment by WoLpH** [comment]
Yes, that's a good point. An identity matrix would make more sense
