### ISSUE TITLE
Tutorial on how to save multiple meshes to a single STL file?

### ISSUE THREAD

**Issue by Skylion007** [WoLpH/numpy-stl#11]
You provide a method to load multiple meshes from a single STL file, but how do you save them? Is this method not implemented? If so, please make this issue a feature request to implement it.

**Comment by WoLpH** [comment]
It's actually fairly easy, just write multiple meshes to the same file :)

For example:
```python

out_fh = open('new_file.stl', 'wb')
for i, mesh in enumerate(Mesh.from_multi_file(filename)):
    mesh.v0 += 10
    mesh.save('mesh_%d.stl' % i, out_fh)
out_fh.close()
```
