### ISSUE TITLE
mesh.from_file throws Assertion Error when open normal small file

### ISSUE THREAD

**Issue by btsrkex** [WoLpH/numpy-stl#110]
System: Linux Mint 19.2 Cinnamon (4.2.3) in VirtualBox
Kernel: 4.15.0-54-generic
Python version: 3.6
I'm using the newest version of all related libraries (six, cython, numpy, etc.)

I've found the closed (and unsolved due to non-reproducible) issues (37 and 52)that very similar, however, those happened with the ascii loader function while the binary loader function failed for me as well.
Different from issue 52 mentioned none of the other errors was raised during the execution.
I tried to alter my locale to C.UTF-8 and it doesn't change anything.

Exception log:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/Project/openscadProject/GUI.py", line 218, in generateCodeFunc
    ifs=c.generateCode()
  File "/usr/Project/openscadProject/feature.py", line 111, in generateCode
    txtsize=self.getminmax(mesh.Mesh.from_file(os.path.join(self.fdir,txtdxffile),speedups=False))
  File "/usr/local/lib/python3.6/dist-packages/stl/stl.py", line 323, in from_file
    fh, mode=mode, speedups=speedups)
  File "/usr/local/lib/python3.6/dist-packages/stl/stl.py", line 93, in load
    name, data = cls._load_binary(fh, header)
  File "/usr/local/lib/python3.6/dist-packages/stl/stl.py", line 108, in _load_binary
    count, MAX_COUNT)
AssertionError: File too large, got 875901486 triangles which exceeds the maximum of 100000000
`

The dxf file I'm trying to open is just some letters generated by solidpython via Openscad, which should have no way to contain that many triangles. Here is the file I mentioned.
[e9d35e8ac9c6ee21d697aa5f38f3340b.zip](https://github.com/WoLpH/numpy-stl/files/3540552/e9d35e8ac9c6ee21d697aa5f38f3340b.zip)

I'd like to measure the length and width of the generated letters but I cannot come up with a way to do so without load the file. I'd like to know if I have any other alternative solutions to achieve my goal.

**Comment by WoLpH** [comment]
The file you've linked is a DXF file, not an STL file. Did you attach the wrong file?
