### ISSUE TITLE
Normals don't seem to change when I rotate a mesh

### ISSUE THREAD

**Issue by nickc92** [WoLpH/numpy-stl#111]
The title says it all, basically.  When you rotate an object, shouldn't its normals change?

**Comment by WoLpH** [comment]
I think you're right, I've added a fix for it: https://github.com/WoLpH/numpy-stl/commit/c1c63e5f7caad80c864000933b3ce4da2f7a82bc

Can you try if that works for you? If so, I'll push out a new release
