### ISSUE TITLE
How to convert STL to IGES ?

### ISSUE THREAD

**Issue by selvakarna** [WoLpH/numpy-stl#112]
How to convert STL to IGES ?

**Comment by WoLpH** [comment]
I have no experience with IGES so I can't add much. But a quick Google gives me PyIGES which seems to support `IGESGeomLine` to draw a line: https://pyiges.readthedocs.io/en/latest/examples/benchmarks/414_0/414-000_benchmark.html

So if you convert all of the STL triangles to lines you should be done :)

**Comment by selvakarna** [comment]
Hi @WoLpH , how to convert a MESH or STL to IGES ?

**Comment by WoLpH** [comment]
The answer remains the same as my previous reply ;)
