### ISSUE TITLE
How to save mesh as step using numpy-stl?

### ISSUE THREAD

**Issue by selvakarna** [WoLpH/numpy-stl#113]
How to save mesh as step using numpy-stl?

**Comment by WoLpH** [comment]
The project is called numpy-stl for a reason, it reads and writes STL files :) 

A quick Google showed me this project though: https://pypi.org/project/aocxchange/
Does that help?

**Comment by selvakarna** [comment]
Thanks to @WoLpH

**Comment by WoLpH** [comment]
> The project is called numpy-stl for a reason, it reads and writes STL files :)
> 
> A quick Google showed me this project though: https://pypi.org/project/aocxchange/
> Does that help?
