### ISSUE TITLE
How to Export Parasolid from Surf/Mesh ?

### ISSUE THREAD

**Issue by selvakarna** [WoLpH/numpy-stl#114]
How to Export Parasolid from Surf/Mesh ?

How to export MESH /SURF TO :

*X3D
*STEP
*VRML
*COLLADA
*DXF
*PARASOLID

**Comment by WoLpH** [comment]
As I've mentioned before: https://github.com/WoLpH/numpy-stl/issues/113#issuecomment-536507809 (and here: https://github.com/WoLpH/numpy-stl/issues/112)

> The project is called numpy-stl for a reason, it reads and writes STL files :)
> 
> A quick Google showed me this project though: https://pypi.org/project/aocxchange/
> Does that help?
