### ISSUE TITLE
solid names converted to lowercase

### ISSUE THREAD

**Issue by dfransos** [WoLpH/numpy-stl#115]
At lines 59 and 152 of stl.py there's a lowercase conversion, to further match a substring to my understanding. 
This causes in turn all the solid names to be converted to lowercase, that's an issue when rewriting the stl after manipulation.
Can we just fix this by temp lowercasing only for the sake of string comparison, without changing the object in place?

**Comment by WoLpH** [comment]
Looks like except for the `solid` check it's all case insensitive anyhow so I see no reason why this can't be fixed :)

I'll create a new release
