### ISSUE TITLE
Areas of faces are all equal to 0.5

### ISSUE THREAD

**Issue by DriesAllaerts** [WoLpH/numpy-stl#122]
Since numpy-stl version 2.11.0, the areas of the faces of an stl mesh object are all equal to 0.5. I believe this is related to the fact that in version 2.11 the normals are normalised to have a magnitude equal to one, but the surface area is calculated based on these normals.

**Comment by WoLpH** [comment]
Yep, you're right that's definitely wrong. I'm creating a new release now :)
