### ISSUE TITLE
failed area calculation due to normals coming back as direction vectors 

### ISSUE THREAD

**Issue by NicoAraujo80** [WoLpH/numpy-stl#124]
When calculating the area in base.py file
`def update_areas(self): `
`        areas = .5 * numpy.sqrt((self.normals ** 2).sum(axis=1))`
`        self.areas = areas.reshape((areas.size, 1))`
self.normals all have magnitudes of one causing areas to be equal to half the amount of triangles in the stl file

The code I used to test this after seeing that a calculation I was making was off  was:
`from stl import mesh`
`stlObject = mesh.Mesh.from_file('40mmcube.stl')`
`stlObject.update_areas()`
`area = stlObject.areas.sum()`

with the area coming back as 6. There are 12 normals 4 pointing in the x, y, and z axis all with a magnitude of 1. I'm assuming that for the area to be calculated properly the normals have a magnitude equal to the area of that triangle. Though I was not able to track down where the normals get calculated.

**Comment by WoLpH** [comment]
I created a new versions 4 days ago that fixed this, I think you might be using the older version :)
https://github.com/WoLpH/numpy-stl/issues/122

**Comment by NicoAraujo80** [comment]
Your right. I had seen that issue and had uninstalled the package and reinstalled it with pip, but the problem still persisted. I thought it wasn't fully fixed.

**Comment by WoLpH** [comment]
As far as I can see it's working properly. Generating half a cube with sides size 1 I get 3 as expected:
```python
from stl import mesh
import numpy

# Create 3 faces of a cube
data = numpy.zeros(6, dtype=mesh.Mesh.dtype)

# Top of the cube
data['vectors'][0] = numpy.array([[0, 1, 1],
                                    [1, 0, 1],
                                    [0, 0, 1]])
data['vectors'][1] = numpy.array([[1, 0, 1],
                                    [0, 1, 1],
                                    [1, 1, 1]])
# Front face
data['vectors'][2] = numpy.array([[1, 0, 0],
                                    [1, 0, 1],
                                    [1, 1, 0]])
data['vectors'][3] = numpy.array([[1, 1, 1],
                                    [1, 0, 1],
                                    [1, 1, 0]])
# Left face
data['vectors'][4] = numpy.array([[0, 0, 0],
                                    [1, 0, 0],
                                    [1, 0, 1]])
data['vectors'][5] = numpy.array([[0, 0, 0],
                                    [0, 0, 1],
                                    [1, 0, 1]])

half_cube = mesh.Mesh(data.copy())
print(half_cube.areas)
print(half_cube.areas.sum())
```

**Comment by NicoAraujo80** [comment]
Yea it works now because I manually changed the files. I don't know much about pip but it doesn't seem to be installing the commit from 4 days ago which solved this problem.

**Comment by WoLpH** [comment]
you're right, looks like something went wrong with the release

I'll create a new release

**Comment by WoLpH** [comment]
Thanks for letting me know the release failed :)

**Comment by NicoAraujo80** [comment]
No problem, glad I could help
