### ISSUE TITLE
Mesh optimisation when combined

### ISSUE THREAD

**Issue by Fliens** [WoLpH/numpy-stl#126]
When combining multiple meshes from stl files there are inner faces remaining.
So for example when placing 10 stl cupes next to eachother the combined mesh has 10 times the faces the original cube has rather than just the same amount of faces but stretched over an cuboid.
Is there an option to optimise the mesh after combining, so that inner faces get removed?

**Comment by WoLpH** [comment]
There are certainly algorithms that can do that, but none that are integrated in this library.

A quick google gave me the PyMesh project which seems to have a bunch of methods of taking care of this: https://pymesh.readthedocs.io/en/latest/api_local_mesh_cleanup.html
