### ISSUE TITLE
Homepage example does not work

### ISSUE THREAD

**Issue by andreasbuhr** [WoLpH/numpy-stl#128]
Hi there,

I just tested the example from your webpage:
https://pypi.org/project/numpy-stl/

I get the error:
```
Traceback (most recent call last):
  File "meshimport.py", line 14, in <module>
    scale = your_mesh.points.flatten(-1)
ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
```

**Comment by WoLpH** [comment]
You're right, it seems numpy has changed the parameters for that function. As far as I can see you can simply omit the `-1` and it should work :)
