### ISSUE TITLE
Rotate (and other manipulation) functions

### ISSUE THREAD

**Issue by hrobeers** [WoLpH/numpy-stl#13]
Hi,

I can't find a function to rotate a mesh. What is the standard way to rotate a mesh?

It would be convenient to expose functions like:
* translate
* scale
* rotate

Thanks for creating this lib!
Hans

**Comment by hrobeers** [comment]
I tried things like:

``` python
M.v0 = T.dot(M.v0.transpose()).transpose()
M.v1 = T.dot(M.v1.transpose()).transpose()
M.v2 = T.dot(M.v2.transpose()).transpose()
```

where T is a 3x3 transformation matrix. But no success.

Do I need to create a new BaseMesh?

This issue can also be solved by documenting how to apply a transformation object on the mesh.

**Comment by hrobeers** [comment]
I got it working with the following code:

```python
    # Read the STL file
    orgMesh = Mesh.from_file(args.stl_file[0])

    # Rotate the vectors
    data = zeros(len(orgMesh.vectors), dtype=Mesh.dtype)
    data['vectors'] = orgMesh.vectors.dot(rotationMatrix(args.rot_x, args.rot_y, args.rot_z))

    # Create and save a mesh with the new vectors
    newMesh = Mesh(data, remove_empty_areas=False)
    newMesh.save("object.stl")

def rotationMatrix(rx, ry, rz):
    # Convert from degrees to radians
    rx = radians(rx)
    ry = radians(ry)
    rz = radians(rz)

    Rx = array([[1,         0,          0],
                [0,         cos(rx),    -sin(rx)],
                [0,         sin(rx),    cos(rx)]])

    Ry = array([[cos(ry),   0,          sin(ry)],
                [0,         1,          0],
                [-sin(ry),  0,          cos(ry)]])

    Rz = array([[cos(rz),   -sin(rz),   0],
                [sin(rz),   cos(rz),    0],
                [0,         0,          1]])

    return Rx.dot(Ry.dot(Rz))
```

However the proposed transformation functions would still be useful for people with less knowledge of algebra.

Are Mesh objects immutable?

**Comment by WoLpH** [comment]
All of the internal data is exposed so scaling and translating the meshes can be done by simply multiplying and adding respectively. The docs are perhaps not as clear as they should about this so I'll add some more usage examples: http://numpy-stl.readthedocs.org/en/latest/stl.html#stl.base.BaseMesh

Either way, give this a try:
```python
# Scale the size of the X axis by doubling it
your_mesh.x *= 2
# Scale the size of the X axis by a half
your_mesh.x /= 2

# Translate the Y axis 2 points
your_mesh.x += 2
# Move the Z axis 2 points
your_mesh.z += 2
```

As for being mutable, all the actual data is stored in a numpy array (`your_mesh.data`) and is accessible and mutable through either that or one of the shortcuts (`v0`, `x`, etc.). I'll push out a new release including a rotation function soon :)

**Comment by WoLpH** [comment]
The latest release has support for rotation as well. Thanks for the feedback!
Here's an example of the usage: https://github.com/WoLpH/numpy-stl#modifying-mesh-objects
