### ISSUE TITLE
Creating Mesh objects from a list of vertices and faces fails on float Positions

### ISSUE THREAD

**Issue by SandUhrGucker** [WoLpH/numpy-stl#134]
You describe on https://pypi.org/project/numpy-stl/ howto "Creating Mesh objects from a list of vertices and faces".

The folowing error ocurs if using float-coordinates:

```
    cube.vectors[i][j] = vertices[f[j],:]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```
**Describe the bug**
Doesnt work with floats (Which is motly used in RL I think).

**Expected behavior**
normal operation.

**To Reproduce**
Just modify some Verticses and Faces coordinates to floats.

**My Platform**
Ubuntu 10Buster tested with python 2.7,with
numpy 1.16.6

Ubuntu 10Buster and  python 3.6, with
numpy 1.18.5

Windows 10 python 3.8.3 with
numpy 1.18.4

**Comment by WoLpH** [comment]
The list of faces in that example reference the vertices, so they shouldn't ever be floats.

Simply put:
 - vertices: a list of x, y and z coordinates
 - faces: list of indices for the above vertices which make up the triangles

**Comment by WoLpH** [comment]
To take a small portion of the example:

```python
vertices = np.array([\
    [-1, -1, -1],  <-- first point of the triangle below
    [+1, -1, -1], <-- last point of the triangle below
    [+1, +1, -1],
    [-1, +1, -1], <-- second point of the triangle below
    [-1, -1, +1],
    [+1, -1, +1],
    [+1, +1, +1],
    [-1, +1, +1]])
# Define the 12 triangles composing the cube
faces = np.array([\
    [0,3,1],
```
