### ISSUE TITLE
Can't open the new .stl file with the quickstart example

### ISSUE THREAD

**Issue by Occupied-Observer** [WoLpH/numpy-stl#135]
Hi thanks for sharing the code and writing the function, I am using the quickstart example to create a new .stl file, I am able to create the new .stl file but cant open the same, maybe it is getting corrupt or so (showing 5KB file). Can someone please help to resolve the same

**Comment by WoLpH** [comment]
You'll need to give a bit more detail before I can help.

1. Which exact example did you use? (adding your entire code works too)
2. What's the exact error you're getting
