### ISSUE TITLE
Can I convert a point cloud data that is .npy to .stl format?

### ISSUE THREAD

**Issue by super233** [WoLpH/numpy-stl#138]
Can I convert a point cloud data that is .npy to .stl format?
If it's ok, then how?

**Comment by WoLpH** [comment]
This has been discussed a few times before and is a bit outside my area of expertise to be honest.

Perhaps you can get something useful out of the previous discussions though:
 - https://github.com/WoLpH/numpy-stl/issues/89
 - https://github.com/WoLpH/numpy-stl/issues/104
 - https://github.com/WoLpH/numpy-stl/issues/19
