### ISSUE TITLE
mesh union of two pieces of cylinders with a common side face

### ISSUE THREAD

**Issue by usrpy** [WoLpH/numpy-stl#139]
Hello,
Assuming the boolean union of two pieces of cylinder with a common side face, as case ,
common cylinders extremities become internal to the resulting mesh body. 
Is it possible to do that using numpy-stl, leading a watertight and not overlapping mesh result.
Does removal of common faces, indicating the plane where these faces are located, before union would be suitable ?
Thank you so much for advice.

**Comment by WoLpH** [comment]
The main goal of this library is storing and loading STL files to a numpy array. After that you can manipulate it any way you want but the library itself doesn't offer many options in terms of manipulation.

There are a few methods for rotation: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.rotate
And transforming a mesh: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.transform
Or translating a mesh: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.translate

But removing common faces is a much more intricate operation. You'll have to write an algorithm for that yourself, but if you create something good I'm open to adding it to the library :)
