### ISSUE TITLE
After version 1.4.0 something changed in the data representation

### ISSUE THREAD

**Issue by Uvar** [WoLpH/numpy-stl#14]
I can't really trace it, will spend some more hours on it, but probably something broke when adding support for python 3.

Error message in one of the scripts:
"Invalid value encountered in double_scalars"
When I try to do 2 * x * y/(x ** 2+y ** 2) with x and y scalars.
In other words: x and y are both zero all of a sudden, and the division is invalid.

This worked without a hitch in version 1.4.0. ^^

**Comment by WoLpH** [comment]
Do you have a full testcase for me? It'll help me find the regression easier :)

**Comment by Uvar** [comment]
In the shared repository: STLRepair\Scripts\Rotate.py executed on the starwars.stl file in the STLFiles folder. Version 1.6 returns original printability 0.602 and optimal 0.681; 1.4 returns 0.681/0.735 and the correctly rotated output STL.

**Comment by WoLpH** [comment]
Sigh... / isn't the same as //

I'm an idiot

**Comment by Uvar** [comment]
^^ Glad to be of help. I'm actually kinda amazed the problem with unit vector calculation being full integers didn't show up with others as well. :+1:  ;)
