### ISSUE TITLE
Rotating stl file with QTimer

### ISSUE THREAD

**Issue by omerenen** [WoLpH/numpy-stl#141]
I can rotate stl file that I've imported. However, when I try to rotate it with QTimer by random number every second, it is not working. Although, random numbers are being written, It is just rotating when I run it, after that it is not. How can I do it?

Code is here : 

```
class Canvas(FigureCanvas, FuncAnimation):
    def __init__(self, parent=None, width=0, height=0, dpi=55):
        self.fig = Figure(figsize=(8, 7.5), dpi=57)
        self.fig.patch.set_facecolor('#efefef')
        self.fig.patch.set_alpha(0)

        FigureCanvas.__init__(self, self.fig)
        self.setParent(parent)
        self.ax6 = self.figure.add_subplot(111, projection='3d')
        self.ax6.get_xaxis().set_visible(False)
        self.ax6.set_xlim(-150,250)
        self.ax6.set_ylim(-200,200)
        self.ax6.set_zlim(0,400)
        self.ax6.set_facecolor('#efefef')

        self.m1 = mesh.Mesh.from_file('assets/uydu.stl')
        self.timerRotation = QtCore.QTimer()
        self.timerRotation.timeout.connect(self.rotator)
        self.timerRotation.start(1000)
        
    def rotator(self):
        self.degree = random.randint(0, 360)
        print(f"{self.degree} degree" )
        self.m1.rotate([0, 1, 0], math.radians(self.degree))
        self.ax6.add_collection3d(mplot3d.art3d.Poly3DCollection(self.m1.vectors,edgecolor='k'))
        scale = self.m1.points.flatten()
        self.ax6.auto_scale_xyz(scale-10, scale+10, scale)
```

**Comment by WoLpH** [comment]
It's really hard to say what's going wrong here, but I can take a wild guess. Are you sure you're redrawing after the rotation?

**Comment by omerenen** [comment]
> It's really hard to say what's going wrong here, but I can take a wild guess. Are you sure you're redrawing after the rotation?

yes, I am

**Comment by WoLpH** [comment]
Perhaps you need to add an argument to `QTimer`? https://doc.qt.io/qtforpython/PySide2/QtCore/QTimer.html

The examples show a parent element being passed. I wouldn't expect it to be garbage collected here but I've had some funky issues with that in the past with Qt and Python.

**Comment by omerenen** [comment]
> Perhaps you need to add an argument to `QTimer`? https://doc.qt.io/qtforpython/PySide2/QtCore/QTimer.html
> 
> The examples show a parent element being passed. I wouldn't expect it to be garbage collected here but I've had some funky issues with that in the past with Qt and Python.

I think, there is no problem when the py file is run because the STL file is rotating when it starts. I wonder why it is not replying to its rotating while the random numbers are being written on the console.

**Comment by omerenen** [comment]
> > Perhaps you need to add an argument to `QTimer`? https://doc.qt.io/qtforpython/PySide2/QtCore/QTimer.html
> > The examples show a parent element being passed. I wouldn't expect it to be garbage collected here but I've had some funky issues with that in the past with Qt and Python.
> 
> I think, there is no problem when the py file is run because the STL file is rotating when it starts. I wonder why it is not replying to its rotating while the random numbers are being written on the console.

**Comment by omerenen** [comment]
![image](https://user-images.githubusercontent.com/60857463/89574546-00697900-d835-11ea-843b-12f9321f767a.png)

![image](https://user-images.githubusercontent.com/60857463/89574564-09f2e100-d835-11ea-800a-55e34f78a0ad.png)

Actually, it is rotating the STL file. I realized it when I change the 3D view position. It creates a new stl view every one second, instead of rotating it.

**Comment by omerenen** [comment]
Problem was solved.

Here is the solution:

`           
            
            self.m1 = mesh.Mesh.from_file('assets/uydu.stl')

            self.timerSim = QtCore.QTimer()

            self.timerSim.timeout.connect(self.rotator)

            self.timerSim.start(1000)
`
`
            
            def rotator (self):

            self.m1.rotate([1, 0, 0], math.radians(pitch_array[-1]-pitch_array[-2]))
            self.m1.rotate([0, 1, 0], math.radians(roll_array[-1]-roll_array[-2]))
            self.m1.rotate([0, 0, 1], math.radians(yaw_array[-1]-yaw_array[-2]))
            self.canvas.ax6.add_collection3d(mplot3d.art3d.Poly3DCollection(self.m1.vectors, edgecolor='k'))
            self.canvas.ax6.auto_scale_xyz([-135, 135], [-135, 135], [-135, 135])
            self.canvas.draw()
            self.canvas.ax6.clear()
`
