### ISSUE TITLE
Scale at file import

### ISSUE THREAD

**Issue by Pentaerythritol** [WoLpH/numpy-stl#144]
Hello ! 

I have an issue with with stl file from Catia V5 where the files are imported in meter instead of millimeters. Is there a solution to scale the whole mesh object without scaling by hand every objects? 

Thanks

**Comment by WoLpH** [comment]
It should be pretty simple actually :)

I think this should work:
```python
stl_file = stl.StlMesh(input_filename)
stl_file /= 1000
stl_file.save(output_filename)
```

**Comment by Pentaerythritol** [comment]
Sorry for the late answer, but it worked nicely, thanks !
