### ISSUE TITLE
rotate function typo

### ISSUE THREAD

**Issue by Uvar** [WoLpH/numpy-stl#15]
silly mistake, but the Euler-Rodrigues matrix is incomplete.
The variables are assigned like:
aa, ab, ac,ad = powers[0:4]
BB, bb, bc, bd = powers[4:8]
CC, cb, cc, cd = powers[8:12]
DD, db, dc, dd = powers[12:16]

Since ba = ab, ca = ac and da = ad; there are no issues in the calculations stemming from this, but it's still a bit silly. ;)

In the same category of silly:
# Rotate 90 degrees over the X axis
meshes[0].rotate([0.0, 0.5, 0.0], math.radians(90)) <- This should be [1., 0., 0.] right? Else you rotate about the y axis.
(and the one right after as well)

**Comment by WoLpH** [comment]
Oops... silly me. Guess I was a bit tired when writing that :P
