### ISSUE TITLE
How to save stl file with color

### ISSUE THREAD

**Issue by ClarkDinh** [WoLpH/numpy-stl#150]
Dear Rick van Hattem,
I would like to ask you how can I save the stl file with color. 
I have vertices and faces. I save the mesh in the same way as your description:
---Create the mesh
cube = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
        cube.vectors[i][j] = vertices[f[j],:]
--- Write the mesh to file "cube.stl"
cube.save('cube.stl')

However, it just saves the grey stl file as the following attachment.
<img width="581" alt="stl without color" src="https://user-images.githubusercontent.com/3078525/99743494-216e8500-2b19-11eb-9244-e8d25c0d805a.png">

How can I save the stl with color as produced by  plot_trisurf.
<img width="503" alt="matplotlib" src="https://user-images.githubusercontent.com/3078525/99743487-1ddafe00-2b19-11eb-91a9-53d4fec4eb4d.png">

Thank you very much for your support.

**Comment by WoLpH** [comment]
The stl format has no support for color at all. It only consists of a list of triangles and a list of combinations of those triangles to build the structures.

The plot appears to be basing the color on the z height.

**Comment by ClarkDinh** [comment]
Thanks for your feedback.

**Comment by eudoxos** [comment]
> The stl format has no support for color at all. It only consists of a list of triangles and a list of combinations of those triangles to build the structures.

[Binary STL](https://en.wikipedia.org/wiki/STL_%28file_format%29#Binary_STL) does have limited (RGB) color support, though it is not standardized.

**Comment by WoLpH** [comment]
That's an interesting new addition. If there's enough interest I can add it to the library but it looks like it would break most STL software

**Comment by eudoxos** [comment]
>  it would break most STL software

No, it uses the 2 `attr` bytes which are normally unused anyway — you are already reading and writing them, too :

https://github.com/WoLpH/numpy-stl/blob/6f2b6f831f3e372878fb2d19bbfe6c029a2001aa/stl/base.py#L175

**Comment by WoLpH** [comment]
I read this and assumed it could be problematic:

> in the standard format, this should be zero because most software does not understand anything else.

But you're right, many libraries probably won't care about it.
