### ISSUE TITLE
Help : Best way to compute normals

### ISSUE THREAD

**Issue by Optimox** [WoLpH/numpy-stl#153]
Hi, thanks for the library!

I'm trying to construct an stl file from a list of vertices and faces.

The example given in the doc seems ok but:

- after iterating on all triangles, `my_mesh.data` only contains `[0, 0, 0]` for the normals. Should I compute them myself manually and do `my_mesh.normals = my_computed_normals` or is there a generic way to compute normal based on the corresponding triangle?

Thank you!

**Comment by WoLpH** [comment]
You can make the mesh recalculate them using [`mesh.update_normals()`](https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.update_normals)

Additionally, all load/open methods support a flag for that as well: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh

**Comment by Optimox** [comment]
Yes thank you, I computed the normals by hand but flags are useful.

Cheers
Seb
