### ISSUE TITLE
Valid stl file (case sensitivity)

### ISSUE THREAD

**Issue by nilswagner** [WoLpH/numpy-stl#155]
Is the file HalfDonut.stl a valid stl file?
solid HalfDonut.stl
...
ENDSOLID HalfDonut.stl

An ASCII STL file begins with the line

solid <name>

The file concludes with 
endsolid <name>

What about case sensitivity of endsolid?

https://en.wikipedia.org/wiki/STL_(file_format)

**Comment by WoLpH** [comment]
As far as I am aware the standard doesn't specify anything about needing either upper or lowercase. I've changed the file as a test for a case sensitivity fix recently: https://github.com/WoLpH/numpy-stl/issues/154

I do believe it's valid but I'm not certain. Up to a week ago this library only supported the lowercase version but it doesn't matter much either way I think.

**Comment by WoLpH** [comment]
The new release supporting case varying STL files is now online :)
