### ISSUE TITLE
Tag 2.15.1 contains version 2.14.2

### ISSUE THREAD

**Issue by frenzymadness** [WoLpH/numpy-stl#165]
Hello.

When I download a file with the source code of this project from this Github URL: https://github.com/WoLpH/numpy-stl/archive/v2.15.1.tar.gz I get an archive where `stl/__about__.py` still contains `__version__ = '2.14.2'` which leads to improper metadata after a build.

Could you please fix the tag?

**Comment by frenzymadness** [comment]
If you compare the tag with the develop branch, you'll see that the commits changing versions landed in develop branch after the tag was created. https://github.com/WoLpH/numpy-stl/compare/v2.15.1...develop

**Comment by WoLpH** [comment]
That's really weird... I have the entire creation of tags automated so I have no clue how this has happened.

What's even stranger, the git tag on my local system does have the correct files.
In any case, I've reuploaded the tag to github and that seems to work: https://github.com/WoLpH/numpy-stl/blob/v2.15.1/stl/__about__.py

**Comment by frenzymadness** [comment]
Thanks for the fix!
