### ISSUE TITLE
STL to segmentation mask

### ISSUE THREAD

**Issue by sulaimanvesal** [WoLpH/numpy-stl#170]
Is there any function that allows us to convert STL to a binary 3D segmentation mask (like a nifty/nrrd file including pixel-spacing) format? this would be very helpful for our task as we have tones of STLs.

**Comment by WoLpH** [comment]
This library primarily focusses on simply saving and loading STL files from your meshes. There are a few basic mesh editing functions included but nothing close to what you're looking for.

And without doing a lot of research I wouldn't know where to start doing something like that efficiently.
