### ISSUE TITLE
Tag v2.16.0 lists version 2.15.1 in stl/__about__.py

### ISSUE THREAD

**Issue by ahesford** [wolph/numpy-stl#173]
Looks like you tagged v2.16.0 before bumping the version in `stl/__about__.py`:

https://github.com/WoLpH/numpy-stl/blob/v2.16.0/stl/__about__.py#L3

**Comment by WoLpH** [comment]
Sorry about this extremely slow response... for some reason it seems that the deploy script I'm using has a bug and creates the tag before committing.

I'm not sure what's causing the issue though... the release on pypi is correct and the local tag files I have appear correct too.
