### ISSUE TITLE
Find a hole in a mesh

### ISSUE THREAD

**Issue by diazGT94** [wolph/numpy-stl#181]
Hi, 

I'm new using .stl models with Python. And I was wondering if I've a model that has two holes is it possible to find the hole dimensions and centroids?

**Comment by WoLpH** [comment]
This library does not provide any functionality for that, but you could do that :)

Here's a useful discussion on stackoverflow: https://stackoverflow.com/questions/12968478/how-to-detect-a-hole-in-the-triangular-mesh
