### ISSUE TITLE
Mesh faces

### ISSUE THREAD

**Issue by AxoyTO** [WoLpH/numpy-stl#184]
Couldn't find any information about extracting the faces of a mesh, how to do it? Is there a function for it? I appreciate the help in advance!

**Comment by WoLpH** [comment]
Here's a very similar question: https://github.com/WoLpH/numpy-stl/issues/164

What it comes down to is that a `Mesh` object has a list of vertices (triangles) which consists of points. Those are effectively the faces.

In addition to that you will probably need the normals as well to know what direction the triangle is pointing to get the face.
