### ISSUE TITLE
How to draw a ball

### ISSUE THREAD

**Issue by 936769651** [wolph/numpy-stl#185]
How do I draw a ball，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you，thank you！

**Comment by WoLpH** [comment]
Generating a sphere itself  is reasonably simple: https://stackoverflow.com/questions/25253719/sphere-mesh-grid-in-python
From that point on however, you will need to do triangulation which scipy can do: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html
