### ISSUE TITLE
AUTOMATIC mode does not work, if header is in ascii

### ISSUE THREAD

**Issue by lucazechner** [wolph/numpy-stl#191]
An solidworks exported stl file contains a header in ascii and the mesh in binary mode. If the stl mesh gets imported (from_file method) with automatic mode, an exception is thrown.
Workaround: manually set the mode to binary, with disadvantage to loose support for ascii files.
Attached is the used sample file from solidworks:
[solidworks sample file.zip](https://github.com/WoLpH/numpy-stl/files/8253710/solidworks.sample.file.zip)

I hadn't much time yet to deep dive into the source, but i assume the issue is somewhere in the bin/ascii detection.
Thanks in advance

**Comment by WoLpH** [comment]
I've had a look at the file but (at least in this case) the issue is that there's no content to the file. It only contains the ascii header and nothing else. Do you have an STL file with a basic mesh perhaps?
