### ISSUE TITLE
numpy-stl how to load stl entity with line fill color

### ISSUE THREAD

**Issue by luoyu-123** [wolph/numpy-stl#196]
numpy-stl how to load stl entity with line fill color，I loaded it like this
picture
![image](https://user-images.githubusercontent.com/59160360/172554815-36c37905-6dfb-4ed8-9fc9-14b15daf40ed.png)
But the effect I want is this
![14](https://user-images.githubusercontent.com/59160360/172554994-1a533284-3465-4952-a572-1130392fd456.png)
how can i make it happen

**Comment by WoLpH** [comment]
It depends on the code you used to render this. This library only handles the storage of t he 3D objects, it does not do any rendering itself
