### ISSUE TITLE
DOC: add a disclaimer that this is not a NumPy-approved nor affiliated project

### ISSUE THREAD

**Issue by mattip** [WoLpH/numpy-stl#197]
A user turned to the [numpy-discussion mailing list](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/HN677JEYS53CJBPGKHIYXJ3ZPZUE47VP/) asking NumPy for help with this library. The NumPy name is a trademark owned by NumFocus, [here are the guidelines](https://numfocus.org/trademark-guidelines) for use of trademarked names. I am not a lawyer, but until this all gets sorted out, it might be nice to at least put into your README and documentation that the library uses NumPy but is not directly associated with it.

**Comment by WoLpH** [comment]
I always assumed it was quite obvious... apparently I was wrong

I've added some text to the readme, but I'm honestly not sure it will help for cases like these...

**Comment by mattip** [comment]
Thanks
