### ISSUE TITLE
How to use `test` modules

### ISSUE THREAD

**Issue by Why-not-now** [wolph/numpy-stl#201]
In [https://numpy-stl.readthedocs.io/en/latest/tests.html#](url), I can see that there are modules to validate your stl files, how do I access it?

**Comment by WoLpH** [comment]
If you clone the Github repository you get all the tests. Specifically, they are over here: https://github.com/WoLpH/numpy-stl/tree/develop/tests

To run the tests you can either use `tox` or you can call `py.test` directly after installing the library test requirements:
```bash
$ pip install -r tests/requirements.txt
```
