### ISSUE TITLE
Z-height 

### ISSUE THREAD

**Issue by agen49** [WoLpH/numpy-stl#202]
Hello,

Thanks to everyone who made this library available to public. 

1) Is there an option to rotate an stll object using x, y, and z angles? If yes, how?

2) Is there an option to find the Z-height of an stl object at a specific orientation? If yes, how?

Thank you. 

P.S. I am new to programming, my background is in environmental engineering.

**Comment by WoLpH** [comment]
1. Yes, take a look at the example of the readme: https://github.com/WoLpH/numpy-stl#modifying-mesh-objects
2. The easiest method I can think of is by rotating first and doing `mesh.z.max() - mesh.z.min()`

**Comment by agen49** [comment]
Thank you for replying back. I appreciate the time. 

1. I've tried to follow the code but I am kinda lost. Would you please post a code example on this page for ONLY the lines of codes that any user can use to rotate their parts?

2. I am getting an error "module 'stl.mesh' has no attribute 'z'"

**Comment by WoLpH** [comment]
```python

from stl import mesh


your_mesh = mesh.Mesh.from_file('tests/stl_binary/HalfDonut.stl')

# Rotate 90 degrees over the Y axis
your_mesh.rotate([0.0, 0.5, 0.0], math.radians(90))

z_height = your_mesh.z.max() - your_mesh.z.min()
```

**Comment by agen49** [comment]
Thank you very much. Honestly, I didn't expect it to be that simple, I thought I needed to copy all the code under "modifying mech objects" and tweak it. Thank you for clarifying that, very kind of you. Have a good day/night.

**Comment by agen49** [comment]
Thank you, when I do double rotation, The Z-height value I get from Numpy-stl is different than the one I get from sliding software, may I ask why? Am I doing something wrong?


# Rotate # degrees over the Y axis
your_mesh.rotate([0.0, 1.0, 0.0], math.radians(15))

# Rotate # degrees over the X axis
your_mesh.rotate([1.0, 0.0, 0.0], math.radians(15))

And I commute the Z-height using:

z_height = your_mesh.z.max() - your_mesh.z.min()
z_height
