### ISSUE TITLE
about projection area

### ISSUE THREAD

**Issue by mickey3721** [wolph/numpy-stl#207]
how to use numpy-stl to calculate model projection area along a given axis ,like along x axis (yz plan) y axis (xz plan) ....

**Comment by wolph** [comment]
This library is mainly meant for reading/writing STL files, whatever calculation you do after that is up to you :)

Having that said, I think stackoverflow might be a better place for your question. Perhaps this would be a nice starting point? https://stackoverflow.com/questions/17836880/orthogonal-projection-with-numpy

Feel free to update your question if you have any numpy-stl specific questions about implementing your algorithm :)

I think you need the `mesh.points` attribute for your endeavour: https://numpy-stl.readthedocs.io/en/latest/stl.html#module-stl.base
