### ISSUE TITLE
shape cant find

### ISSUE THREAD

**Issue by Sittihel** [wolph/numpy-stl#208]
when i use it, code have a error

Traceback (most recent call last):
  File "/Users/sittihel/PycharmProjects/pythonProject/main.py", line 26, in <module>
    mesh_data.vectors[i] = mesh.Sphere(positions[i], sizes[i]).data
                           ^^^^^^^^^^^
AttributeError: module 'stl.mesh' has no attribute 'Sphere'

what shall i do?

**Comment by wolph** [comment]
I'm not sure where you got that code from, but this library has never had a Sphere function anywhere :)

You're probably confusing this library with a different one
