### ISSUE TITLE
Can we check if two different stl files are overlapping each other

### ISSUE THREAD

**Issue by arslan437** [wolph/numpy-stl#211]
Hi WoLph

I want to place multiple stl file to one stl file. I am loading the files individually than translating them close to each other. Currently I am translating the stl files based on bounding box. But I want to pack more stl files into less space. Is there any way I can check if the two stl files overlap each other after translating the one file close to other one.

**Comment by wolph** [comment]
I would personally create an octree or kd-tree per mesh and use those to test if there's overlap between the two. Because they are trees the search will be logarithmic in time complexity.

That's at least the fastest way I can think of...
