### ISSUE TITLE
Merge STL question

### ISSUE THREAD

**Issue by DrPepper1234** [wolph/numpy-stl#214]
Thank you for the work, it does a great job manipulating STL file. Is there a way to merge multiple STL files into one STL that is a single body? Right now I have some STL that import as separate bodies but would prefer a single body .
Thank you

**Comment by wolph** [comment]
A Mesh object is simply a collection of points and consequent triangles so merging them can be as simple as concatenating them. This example demonstrates it: https://github.com/wolph/numpy-stl#extending-mesh-objects

Specifically:
```python

cube = mesh.Mesh(numpy.concatenate([
    cube_back.data.copy(),
    cube_front.data.copy(),
]))
```

**Comment by DrPepper1234** [comment]
Maybe my question was not phrased properly. Say I have two cubes, one with side of 1mm and one with side of 10mm, both being centered in origin, 0,0,0. If I concatenate the two meshes and save the stl, when importing the stl file in say SolidWorks I get two distinct meshes that SW will use to generate 2 bodies. What I would like is a single body so only a single all encompassing mesh.
The example above is a simple one but imagine meshes that just intersect and not included into each other.
Guess I'm after some sort of boolean operation but my programming expertise is limited, I'm a mechanical designer.

**Comment by wolph** [comment]
Ah, I misunderstood. That is certainly possible but it's a fairly complex operation and not something this library does out of the box.

I would suggest looking at the solutions offered by this stackoverflow question: https://stackoverflow.com/questions/51476722/intersection-3d-meshes-python

**Comment by DrPepper1234** [comment]
Thank you for providing the link, seems it would help.
