### ISSUE TITLE
More info needed on stl atributes

### ISSUE THREAD

**Issue by cdinea** [wolph/numpy-stl#218]
hi.

Can you add more information on what v0,v1,v2 ..represent in this code?

your_mesh.v0, your_mesh.v1, your_mesh.v2

Thanks.

**Comment by wolph** [comment]
The `v0`, `v1` and `v2` are the vectors and they come straight from the STL files.

Simply put, a triangle consists of 3 points and the vectors contain those 3 points. For ease of use you can also use `your_mesh.points` which reshapes the data into `x0, y0, z0, x1, y1, z1, x2, y2, z2`
Or you can use `your_mesh.x` for all of the `x` coordinates and so on for y and z.

**Comment by wolph** [comment]
Perhaps this bit of the documentation might help a little: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.base.BaseMesh
