### ISSUE TITLE
the centroids of a stl file was not update after i rotated the stl file

### ISSUE THREAD

**Issue by xuwenhua4202** [wolph/numpy-stl#219]

**Comment by wolph** [comment]
The centroids are not updated automatically for performance reasons. You can easily update it using the `update_centroids` method though:
https://github.com/wolph/numpy-stl/blob/26c9332427de1d49aefb6831b1073e3d3ed71ce3/stl/base.py#L348-L349

Or call the `update_normals` method which updates the centroids as well by default
