### ISSUE TITLE
loading an stl file

### ISSUE THREAD

**Issue by AlexLee** [WoLpH/numpy-stl#22]
@WoLpH I tried to run the example but I get an error message stating that "mesh" in the mesh.Mesh_from_file method is not defined. Also, I noticed there was nothing in the stl/mesh module
```
import numpy
from stl import mesh
your_mesh = mesh.Mesh.from_file('some_file.stl')
```

I tried modifying the code but I get an error message stating that "module object has no attribute "from file" "

```
import numpy
import stl
your_mesh = stl.from_file('some_file.stl')
```

**Comment by AlexLee** [comment]
d

**Comment by WoLpH** [comment]
It's most likely that you have a different stl module installed.

Try `pip uninstall stl` and `pip uninstall numpy-stl`. After that reinstall the module with `pip install numpy-stl`

**Comment by AlexLee** [comment]
@WoLpH  Thanks for the reply. How come the Mesh class only has a placeholder? That might be why `your_mesh = mesh.Mesh.from_file('some_file.stl')` is not working

**Comment by WoLpH** [comment]
It's not just a placeholder, if you look careful you'll see that it inherits `stl.BaseStl`: https://github.com/WoLpH/numpy-stl/blob/master/stl/stl.py#L33

The Mesh name is a logical name for usage, the BaseStl contains the stl file reading and the actual mesh code is in BaseMesh: https://github.com/WoLpH/numpy-stl/blob/master/stl/base.py#L55

**Comment by AlexLee** [comment]
@WoLpH Thanks for the follow up. So what would be the correct way of calling the `from_file` method? 

As you suggested, I typed `pip uninstall stl` to make sure there wasn't an additional "stl" library installed (there wasn't) and then I typed `pip uninstall numpy-stl`. Then I reinstalled numpy-stl `pip install numpy-stl`

I am using the example listed in "Quickstart". `your_mesh = mesh.Mesh.from_file('some_file.stl')` gives me an error message stating that "mesh is not defined"

**Comment by WoLpH** [comment]
The example in your original question is correct and should function without any problems:
```
import numpy
from stl import mesh
your_mesh = mesh.Mesh.from_file('some_file.stl')
```

If it doesn't than I would recommend checking what is imported when you run the code. A conflict with a different module seems likely:
```
import stl
print 'stl file', stl.__file__
from stl import mesh
print 'mesh file', mesh.__file__
```

**Comment by AlexLee** [comment]
@WoLpH  Thanks again.the issue might be with the STL file that I am using. I get an error message

> TypeError: 'NoneType' object is not iterable 


I just used one of your example stl files (star.stl) and it worked fine

Do the stl files need to be water tight,manifold? Are there any other criteria that the stl files need to meet?

**Comment by WoLpH** [comment]
It shouldn't need a specific format, any type of STL file should function. Would you be able to add to upload the STL file here?

**Comment by AlexLee** [comment]
see attached. one has holes filled, the other does not.
[Archive.zip](https://github.com/WoLpH/numpy-stl/files/191305/Archive.zip)

**Comment by AlexLee** [comment]
@WoLpH were you able to load the stl files that I posted?

**Comment by WoLpH** [comment]
Sorry @AlexLee, haven't had the time yet. I'll look at it soon.

**Comment by Gjacquenot** [comment]
I succeed in loading both files with MeshLab.
With `numpy-stl`, I could just open and load 'plane_quadric6.stl'

    from stl import mesh
    m=mesh.Mesh.from_file('plane_quadric6.stl')

The other file creates problem:

    m=mesh.Mesh.from_file('plane_noholes.stl')
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-31-47d6ca79bd4e> in <module>()
    ----> 1 m=mesh.Mesh.from_file('plane_noholes.stl')
    
    C:\Python27\lib\site-packages\stl\stl.pyc in from_file(cls, filename, calculate_normals, fh, mode, **kwargs)
        272         else:
        273             with open(filename, 'rb') as fh:
    --> 274                 name, data = cls.load(fh, mode=mode)
        275
        276         return cls(data, calculate_normals, name=name, **kwargs)
    
    TypeError: 'NoneType' object is not iterable

**Comment by Gjacquenot** [comment]
I figure out where is the problem. The header of the file `plane_noholes.stl` is an empty string of 80 characters. 

In this case, the following instructions in file `stl.py` causes a premature return 

        if not header.strip():
            return

I will try to propose a patch that does not break the tests...

@WoLpH : Maybe you can explain the reason of this test?

**Comment by Gjacquenot** [comment]
@WoLpH :  I have tried deleting these two lines, but I break the current tests (See PR #29)
@AlexLee : For the time being, you can load your STL file `plane_noholes.stl` by changing the header of this file: open the file with a text editor, replace the first space with any another character, save it and then you can load it with `m=mesh.Mesh.from_file('plane_noholes.stl')`. When this bug will be fixed, you won't have to do this nasty operation.

**Comment by WoLpH** [comment]
@Gjacquenot I suppose there is no real reason for that test. There is nothing in the (ill-defined) binary STL standard that requires a header to have content.

To fix the tests I believe an additional test should be added to the code. Instead of:
```
count, = struct.unpack(s('@i'), b(fh.read(COUNT_SIZE)))
```

Something along the lines of:
```
count_data = fh.read(COUNT_SIZE)
if len(count_data) != COUNT_SIZE:
    count = 0
else:
    count, = struct.unpack(s('@i'), b(count_data))
```

**Comment by WoLpH** [comment]
Also, thank you very much for helping out :)
It's greatly appreciated!

**Comment by Gjacquenot** [comment]
@AlexLee : With PR #29 , your binary files can directly be loaded!

**Comment by Gjacquenot** [comment]
@WoLpH, @AlexLee : I think it can now be closed

**Comment by WoLpH** [comment]
The pull request has been merged so I think this issue has been resolved. If not, please let me know @AlexLee :)
