### ISSUE TITLE
How can i find linear parameters of stl model?

### ISSUE THREAD

**Issue by PeterBan11** [wolph/numpy-stl#220]
#I tried this code:
```python
your_mesh = mesh.Mesh.from_file('dog.stl')
xyz = (your_mesh.max_ - your_mesh.min_)

len = xyz[0]
wid = xyz[1]
heig = xyz[2]
```

#Is it correct? 
#What is the length measured in your libraries? Is it measured in millimeters?

**Comment by wolph** [comment]
It's slightly more complicated than that unfortunately. STL files are composed of triangles so you need to make sure you compare each point to each other point.

You are currently comparing the first point of each triangle while ignoring the other 2 points. This will be close to the actual number, but it will usually differ slightly.
To get the correct calculation you need to use `your_mesh.points`

The STL format does not specify a unit so the sizes can be measured in millimeters, meters, inches or something completely different depending on your source. Having that said, most of the 3D print STL files you can find online are in millimeters but there is no guarantee for that.
