### ISSUE TITLE
compatible with Python 3.3?

### ISSUE THREAD

**Issue by AlexLee** [WoLpH/numpy-stl#23]
@WoLpH is numpy-stl compatible with Python 3.3.2? I created a virtual environment with anaconda and I tried to install numpy-stl via `conda install -c https://conda.anaconda.org/prkrekel numpy-stl` (https://anaconda.org/prkrekel/numpy-stl) 

but I get the following error messages

![numpystl_python33](https://cloud.githubusercontent.com/assets/3451840/14069776/404e5d3a-f46c-11e5-8602-d7b995d113f0.jpg)
![numpystl_python33_pic2](https://cloud.githubusercontent.com/assets/3451840/14069777/46aedb0a-f46c-11e5-979d-5af63fe6eab8.jpg)

**Comment by WoLpH** [comment]
It's currently not tested on python 3.2 because it had some conflicts and I
didn't expect many people to use it. But it shouldn't be too hard to get it
up and running. I'll see if I can create a new release before the end of
the week.

**Comment by WoLpH** [comment]
I've given it a little test and it should indeed work. But that conda package seems really out of date. I've published my own conda package: https://anaconda.org/wolph/numpy-stl

**Comment by AlexLee** [comment]
thanks for posting that, is it compatible with python 3.3? i'll give it a try here in a moment

**Comment by WoLpH** [comment]
Yes, it's tested for 3.3

**Comment by WoLpH** [comment]
As far as I can see it functions perfectly in Python 3.3. Feel free to reopen if it doesn't :)
