### ISSUE TITLE
RuntimeError: (False, 'Unable to find more lines')

### ISSUE THREAD

**Issue by xnuohz** [WoLpH/numpy-stl#230]
Load a file with 300k lines and got error
```
import numpy as np
import stl


stl_file = './000000_tumoredbrain.stl'
# Load the STL file
stl_mesh = stl.Mesh.from_file(stl_file, mode=stl.Mode.ASCII)

# Extract vertices and faces
vertices = stl_mesh.vectors.reshape(-1, 3)
faces = np.arange(len(vertices)).reshape(-1, 3)
```

**Comment by wolph** [comment]
Are you sure it's an ascii (text) STL file? If it is ascii file than it's likely damaged.

If you don't specify the mode it should automatically detect your filetype.

**Comment by xnuohz** [comment]
If I don't set the mode, it will get too large error.
https://github.com/wolph/numpy-stl/issues/143

**Comment by wolph** [comment]
Let's try a forced binary mode in that case:
```
mesh = stl.Mesh.from_file(filename, mode=stl.Mode.BINARY)
```

**Comment by xnuohz** [comment]
still the same error "AssertionError: File too large, got 757086002 triangles which exceeds the maximum of 100000000".
the stl file is like this
```
solid Visualization Toolkit generated SLA File
 facet normal -0.26266389071378027 -0.066439483325182305 -0.96259725512312888
  outer loop
   vertex 127.28118896484375 148.48989868164062 3.6938681602478027
   vertex 126.85121917724609 147.91717529296875 3.8507239818572998
   vertex 126.60086059570312 148.54000854492188 3.8760507106781006
  endloop
 endfacet
 facet normal -0.084717307155078608 -0.20353720186408453 -0.97539509191185236
  outer loop
   vertex 126.85121917724609 147.91717529296875 3.8507239818572998
   vertex 127.28118896484375 148.48989868164062 3.6938681602478027
   vertex 127.40935516357422 147.97850036621094 3.7894506454467773
  endloop
 endfacet
.....
```

**Comment by wolph** [comment]
That is an ascii file so it's probably damaged somehow. The user in #143 fixed it using ideamaker, I would suggest using a repair tool to get it fixed.

If you can share your STL file I can also take a look and perhaps make the library a bit more resilient to broken files.

**Comment by ZuheyrAlsalihi** [comment]
Hello, can I please unsubsidized? Thank you

**Comment by xnuohz** [comment]
@wolph Here it is:)
https://uni-duisburg-essen.sciebo.de/s/HeShw1G4da15OOZ/download?path=%2F&files=000000_tumoredbrain.stl

**Comment by alsalihi** [comment]
Hello!

Can you please help me unsubscribe from your list ? I try and get

Whoops! That unsubscribe link isn't valid for your account.

I do not understand why.

Many thanks in advance and kindest regards,

Dr. Zuheyr Alsalihi
Senior Research Eng.
von Karman Institute
72, Chee. de Waterloo
1640 Rhode-St-Genese, Belgium.
+32 359 98 65
+32 473 69 32 27
________________________________

**Comment by wolph** [comment]
@alsalihi In that case you might be logged in with the wrong user/email address. If you're logged in correctly you should have this button:
![image](https://github.com/user-attachments/assets/a14796f9-4a2b-47a8-9d74-af2eb0eb1862)

If that doesn't work than I recommend contacting github support, it's not something I can change for you.


@xnuohz I've tried to open your file and I have no issues. Can you try downloading it again? Perhaps it got damaged during download?

After adding this to your script:
```
print(stl_mesh)
print(vertices)
print(faces)
```
I get these results:
```
<Mesh: b'Visualization Toolkit generated SLA File' 225344 vertices>
[[127.28119   148.4899      3.6938682]
 [126.85122   147.91718     3.850724 ]
 [126.60086   148.54001     3.8760507]
 ...
 [127.52576   136.14986   149.16902  ]
 [126.96575   136.04405   149.13438  ]
 [127.428795  135.67447   149.28871  ]]
[[     0      1      2]
 [     3      4      5]
 [     6      7      8]
 ...
 [676023 676024 676025]
 [676026 676027 676028]
 [676029 676030 676031]]
```

If that still doesn't work than there might be some other issue. Here's the start of the file hash for me so you can verify it's integrity:
![image](https://github.com/user-attachments/assets/1c0ee950-9bb6-49e0-9048-8861e8f783cc)

**Comment by xnuohz** [comment]
Thanks, I'll try it again!
