### ISSUE TITLE
Ascii stl solid names handling

### ISSUE THREAD

**Issue by la7low** [WoLpH/numpy-stl#24]
Hello,

firstly, many thanks for your work and the package!
I would like to read a big ascii stl and would like to modify the part names in it.
The stl has the usual form:
solid part1
  facet normal -1.00000E+000 6.25745E-015 1.16257E-014
    outer loop
      vertex 1.08800E+003 -3.51005E+002 5.06590E+002
      vertex 1.08800E+003 -3.51005E+002 5.26148E+002
      vertex 1.08800E+003 -3.38068E+002 5.19185E+002
    endloop
  endfacet
...
endsolid part1
solid part2
...

How can I get the part names (which come after the solid strings) from the mesh.Mesh.from_file(stlfile) object?
I had a quick look at the documentation but could not find an attribute where they are stored or a method that would returned them.
Also, when writing out the ascii stl again can I provide my own part names?

Thanks in advance,
Lazlo

**Comment by WoLpH** [comment]
Reading the names is supported through the `from_multi_file` method: http://numpy-stl.readthedocs.org/en/latest/tests.html#tests-test-multiple-module

The function itself: http://numpy-stl.readthedocs.org/en/latest/_modules/stl/stl.html#BaseStl.from_multi_file

The mesh objects returned have a name attribute which will be used while storing. Simply modify `your_mesh.name` and store them again. 

Storing is similarly easy: https://github.com/WoLpH/numpy-stl/issues/11

**Comment by WoLpH** [comment]
Effectively, for your case:

```
output_file = open('new_file.stl', 'wb')
meshes = Mesh.from_multi_file(filename)
mesh_a = next(meshes)
mesh_a.name = 'some name for mesh A'
mesh_b = next(meshes)mesh_a.name = 'some name for mesh A'
mesh_c = next(meshes)

for mesh in enumerate(Mesh.from_multi_file(filename)):
    mesh.v0 += 10
    mesh.save(your_new_name, out_fh)
output_file.close()
```

**Comment by la7low** [comment]
Thanks Mr. Wolph for your answers!
(Did you choose your name after Mr Wolf (the problem solver) from Pulp fiction?)

So I tried the following but have a problem with it:
`stlmesh_objects = mesh.Mesh.from_multi_file(stlfile, calculate_normals=False, mode=stl.ASCII)
for mesh_obj in stlmesh_objects:
    print(mesh_obj.name)`

the name of the first mesh is printed fine but the name of the second mesh was not found (or was an empty string and the BaseStl.load method used the binary reader (_load_binary) as the header of the second mesh did not start with 'solid'). I also printed the header in the beginning of the BaseStl.load method and I got this for the second mesh:
b'p\r\n  endfacet\r\n  facet normal 1.00000e+000 0.00000e+000 0.00000e+000\r\n    outer '
So somehow the ascii_reader did not get till the 'endsolid' for some reason. Can I send you the stl file (90kB) and could you please have a look at it?

Thanks, Lazlo

**Comment by WoLpH** [comment]
> Thanks Mr. Wolph for your answers!
> (Did you choose your name after Mr Wolf (the problem solver) from Pulp fiction?)
No, it's actually a remnant from a very long time ago when I still played Wolfenstein 3D. But you're not the first to ask the question, it suits just as well :)

I'll have a look at the STL somewhere tomorrow.

**Comment by WoLpH** [comment]
Ok.. that took a lot longer than I had hoped. Something weird is happening with your STL file and I'm not entirely sure why it's being detected incorrectly.

Somehow it's reading the file as binary instead of ascii, even though you specify ASCII...

**Comment by la7low** [comment]
Thanks for having a look! Yeah, it is strange. But it starts reading in ascii and even I could print the part name of the first solid part but the reader does not go up to 'endsolid' for some reason but gets stuck at a facet normal. And then the code thinks the next solid block starts there but the reader falls back to binary as the line does not start with 'solid'...
I did not see any problems in the STL format and I could read in the STL to a well-accepted CFD (computational fluid dynamics) tool without any problems and the STL itself is coming from a popular tool too.
How to proceed? Will you have another look? Can I help somehow (e.g. by telling you more precisely where the code failed) ?

**Comment by WoLpH** [comment]
It's most likely a silly bug somewhere in the code but I need to hunt it down...

What could help is knowing your exact environment. The Python version, distribution and the operating system.

**Comment by la7low** [comment]
python -V
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)
(numpy-stl installed with pip)

arch linux:
uname -a
Linux  4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

Tell me if you need any other info or if I can help in anything else! Thanks in advance!

**Comment by la7low** [comment]
found the bug:
The fh reads in chunks of buffer size and the size of a part (solid to endsolid section) is not necessarily divisible by BUFFER_SIZE so it read beyond the first 'endsolid' thus the next time the load method was called it read the header (which should start at solid) already somewhere from the next part.
Pull request added as well.

**Comment by WoLpH** [comment]
I've merged your changed with a few adjustments. Can you test the current develop branch just to be sure? It works for me when running a simple test:

```
from stl import mesh, stl


stlmesh_objects = mesh.Mesh.from_multi_file(
    'test_stl_read.stl', calculate_normals=False, mode=stl.ASCII)
for mesh_obj in stlmesh_objects:
    print(mesh_obj.name)
```

**Comment by la7low** [comment]
Thanks, great. This was my first ever contribution to a python package :).
I will test it tonight but should work.
By the way, how come in python3 the relative seek did not work? Is it really so? I use python 3 and it wroked for me...anyway it's not a big deal.
By the way, I am a bit concerned about the newline character handling:
-on windows: \r\n, there would be a trailing \r in the name of the stl parts and at the end of all lines, don't know how much it would affect the normal and vertex readings
-on mac: \r, so your code would not work as you hardcoded split('\n')
-on linux it works and that's what matters for me but maybe you care about the other platforms too...

**Comment by WoLpH** [comment]
Congratulations! Great first contribution :)

To make the local testing easier you can use `tox`. This project has a tox configuration file which will automatically test the documentation, code quality and the code itself on python version 2.7, 3.3, 3.4 and 3.5 if available.

As for the relative seek, Python 3 does support relative seeking in files but only when the file is opened in binary mode. Most likely due to characters not being fixed size with unicode and such.

For the Windows version it is indeed possible that there is a \n and \r so perhaps it's better to search backwards for the regex ` \n\r?solid`. The mac `\r` isn't really an issue, that was only the case for Apple's OS before OS X which was over 15 years ago :)

I'll amend the code a bit to search slightly smarter :)

**Comment by WoLpH** [comment]
I've checked the code but since it's only splitting by newline it shouldn't be a problem in any case :)

It's fixed in the new release
