### ISSUE TITLE
Documentation unclear on auto-computation of normals

### ISSUE THREAD

**Issue by joe-jordan** [WoLpH/numpy-stl#25]
I have a 3D model I want to save from Python, which has lots of holes in the middle. Your module looks like the best way to write out the file. However, after reading this:

http://www.fabbers.com/tech/STL_Format

it looks as though the normal direction is (as I suspected) significant in the output format, in that it must point from solid phase to empty space. Obviously, there are two choices of normal for any set of three coordinates.

You don't seem to have documented a way to initialise from data containing both the facets and their normals (claiming you auto-compute them.) I would very much like to know how your code does this, as it would be non-trivial to do so from the vectors and facets in my system alone.

If there is already a manual way to specify the facet normals when initialising the `stl.mesh.Mesh` class, I would be grateful if you could explain it here, and perhaps amend the documentation to reflect that.

Thanks!

**Comment by joe-jordan** [comment]
I have just had a look at the code, you seem to be computing normals based on the convention about the cyclic ordering of the vertices in the facets. I guess this clears things up; perhaps this should be spelled out in the docs, for newbies to the format like me.

**Comment by WoLpH** [comment]
If you have any suggestions for documentation, a pull request is greatly appreciated :)

Anything that can be improved is welcome.
