### ISSUE TITLE
Saving scaled stl file

### ISSUE THREAD

**Issue by billy0329** [WoLpH/numpy-stl#26]
hi, 

Is numpy-stl capable of saving a scaled stl file?
I mean I opened an stl file, then scaled it. 
Will I be able to save this scaled object as another stl file?

Thanks in advance.

**Comment by WoLpH** [comment]
Yes, that's easily possible. You can scale by every dimension separately with just a few simple lines of code:

```
from stl import mesh
# Specify the stl file you wish to scale here
your_mesh = mesh.Mesh.from_file('mobius.stl')

# Scale X by making it 10 times smaller
your_mesh.x /= 10

# Save the scaled version
your_mesh.save('mobius_scaled.stl')
```
