### ISSUE TITLE
Error in numpy-stl

### ISSUE THREAD

**Issue by immi1988** [WoLpH/numpy-stl#3]
Hello, 

I got an error with your stl.py.
I just installed numpy-stl and got this error:
>>> from stl import stl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\stl\stl.py", line 58
    except RuntimeError, (recoverable, e):
                       ^
SyntaxError: invalid syntax

I'm using Win 8.1 and Python 3.4.2.

I tried to fix the error with deleting the ',' but then another error occurs;
>>> from stl import stl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\stl\stl.py", line 157
    except AssertionError, e:
                         ^

May you fix that error or help me to fix it? 
Thanks in advance.

**Comment by WoLpH** [comment]
Hi,

The problem is that the library currently only supports python 2 and you
are using python 3.

Perhaps I will add python 3 support in the future but right away.

Do you require python 3 or is it possible to settle for python 2 for the
time being?

**Comment by immi1988** [comment]
Hi, 

thank you for your fast support!!!
I think I will use Python 2.

**Comment by sirgogo** [comment]
i need python 3 :(. 

any idea when this might be released?

**Comment by WoLpH** [comment]
Hi @sirgogo, it's on the shortlist for fixing (see #9). I'm hoping to have it fixed before the weekend but it's proving to be slightly less trivial than I would hope. The unicode and bytes handling of Python 3 is significantly different from Python 2. THe result is that trying to get it to work by itself is already a problem but getting it to work in both is definitely a bit tricky.

**Comment by sirgogo** [comment]
@WoLpH , i see. no worries, i'm rooting for you!

while we're here, maybe i could ask you an orthogonal question related to STL files..  do you know a good way to (1) read in a STL file, and (2) check if a given point lies within an object (if so, which object?) ?

essentially, i'm asking how to read/use STL files in Python. Something like rendering the whole model as a 3-D numpy matrix would work too. i need to query the space and find where which material each point belongs to.

**Comment by WoLpH** [comment]
Well, (1) is easy using this library. (2) is notoriously difficult to do,
to properly know if a point is within an object you need to check the
entire hull to see what's the actual "inside" of the object while keeping
in mind that you don't know which side of a triangle is the inside.

Example of a very difficult problem to solve. What would happen if you have
a sphere with a sphere inside it cut out, is the center of both spheres
"inside" the object or not?

For (2) the best way is probably to see if the point is within the convex
hull of an object, but it's not actually a correct solution.

**Comment by WoLpH** [comment]
@sirgogo version 1.5 adds Python 3 support :)
