### ISSUE TITLE
Include my example code?

### ISSUE THREAD

**Issue by nmz787** [WoLpH/numpy-stl#33]
I wanted to duplicate an STL I downloaded, so I could print many of the item using a single 3D-printer print-job. I also tested with combining different STL files into the same output, and included those operations as comments. The script is here:
https://gist.github.com/nmz787/be850c63e7cab3739c79821bfac0c6f4

Thanks for the library! I was so happy to get this STL file duplicated!

**Comment by WoLpH** [comment]
Nice example, I've added it to the readme :)
