### ISSUE TITLE
Link in build.cmd is broken

### ISSUE THREAD

**Issue by petebachant** [WoLpH/numpy-stl#38]
May have been moved to https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by WoLpH** [comment]
Unfortunately this is a bit hard to test for me as I don't run Windows myself. But I'll check it out.

A new appveyor build has just started so we'll see what that returns: https://ci.appveyor.com/project/WoLpH/numpy-stl

**Comment by petebachant** [comment]
Actually I just meant the link to the Cython wiki in the comments of the script. It's a very minor issue of course!

**Comment by WoLpH** [comment]
Ah, I see. Thanks for the heads up. It's fixed now :)
