### ISSUE TITLE
AttributeError: type object 'Mesh' has no attribute 'logger'

### ISSUE THREAD

**Issue by jtprobst** [WoLpH/numpy-stl#40]
When reading an STL file without a name or space after `solid`, numpy-stl wants to warn me

``` python
        if not line.startswith(b('solid ')) and line.startswith(b('solid')):
            cls.warning('ASCII STL files should start with solid <space>. '
                        'The application that produced this STL file may be '
                        'faulty, please report this error. The erroneous '
                        'line: %r', line)
```

However, this fails with

``` python
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    stlmesh = mesh.Mesh.from_file(args.input_file)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 316, in from_file
    fh, mode=mode, speedups=speedups)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 69, in load
    fh, header, speedups=speedups)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 215, in _load_ascii
    name = next(iterator)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 178, in _ascii_reader
    'line: %r', line)
  File "/usr/local/lib/python3.5/dist-packages/python_utils/logger.py", line 46, in warning
    cls.logger.warning(msg, *args, **kwargs)
AttributeError: type object 'Mesh' has no attribute 'logger'
```

Note that in my personal opinion it would be highly desirable to configure the level of strictness when reading STLs. The current implementation adheres to the standard which is good. However, many defective CAD tools fail to obey the specifications and it would be helpful if numpy-stl could adapt to these cases as well.

Installation Details:
- Python 3.5.2 (default, Sep 10 2016, 08:21:44) [GCC 5.4.0 20160609] on linux
- OS Ubuntu 16.04
- numpy-stl==2.0.0
- python-utils==2.0.0

**Comment by jtprobst** [comment]
Reproducible with the following input
```
solid
 facet normal -0.678654 0.294209 -0.672956
  outer loop
   vertex 2.83527 0.679788 0.179586
   vertex 2.81848 0.674862 0.194367
   vertex 2.81848 0.707356 0.208573
  endloop
 endfacet
endsolid
```

**Comment by WoLpH** [comment]
`Note that in my personal opinion it would be highly desirable to configure the level of strictness when reading STLs. The current implementation adheres to the standard which is good. However, many defective CAD tools fail to obey the specifications and it would be helpful if numpy-stl could adapt to these cases as well.`
I believe it does actually. This is a warning, not an error :)

Having that said, I don't understand how you are getting this error as it's running just fine when I try for myself. Just to be sure some data isn't lost, can you try attaching the stl file as a file instead of within the comments? You can drag the file to the textarea :)

**Comment by jtprobst** [comment]
Sure, thanks for looking into this! The file is attached, however I had to use `.txt` as ending because of github. Shouldn't make any difference though. The gist seems to be that there is no space after `solid` which makes numpy-stl emit a warning which then fails for some reason.

```
$ python3
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stl import mesh
>>> m=mesh.Mesh.from_file("attributeerror.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 316, in from_file
    fh, mode=mode, speedups=speedups)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 69, in load
    fh, header, speedups=speedups)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 215, in _load_ascii
    name = next(iterator)
  File "/usr/local/lib/python3.5/dist-packages/stl/stl.py", line 178, in _ascii_reader
    'line: %r', line)
  File "/usr/local/lib/python3.5/dist-packages/python_utils/logger.py", line 46, in warning
    cls.logger.warning(msg, *args, **kwargs)
AttributeError: type object 'Mesh' has no attribute 'logger'
```

[attributeerror.txt](https://github.com/WoLpH/numpy-stl/files/546332/attributeerror.txt)

**Comment by WoLpH** [comment]
Well, I've been able to reproduce it. Apparently it's broken for Linux but works on OS X. And I have absolutely no idea why that is.

```
Python 3.5.2 (default, Sep  5 2016, 17:28:01)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from stl import mesh
>>> m = mesh.Mesh.from_file('attributeerror.txt')
>>> m.data
array([ ([-0.0005502717103809118, 0.0002385173866059631, -0.0005455705686472356], [[2.8352699279785156, 0.6797879934310913, 0.1795859932899475], [2.8184800148010254, 0.6748620271682739, 0.19436700642108917], [2.8184800148010254, 0.7073559761047363, 0.20857299864292145]], 0)],
      dtype=[('normals', '<f4', (3,)), ('vectors', '<f4', (3, 3)), ('attr', '<u2')])
```

Guess I'll have something to debug ;)

**Comment by WoLpH** [comment]
@jtprobst can you try the latest develop branch? I think I've worked around it but I have no clue why Python is behaving different on Linux.

**Comment by jtprobst** [comment]
@WoLpH it works now. I tested it in Docker (`python:latest`), version Python 3.5.2 (default, Nov  1 2016, 00:10:05).
I did a quick review of https://github.com/WoLpH/numpy-stl/commit/39d1a7d49f9c1c1c190af25309603ad2e7950541. I cannot readily explain why it makes the issue disappear.

I'd like to share my personal opinion on the design: I would rather not use the `logged` decorator, nor the `logger.Logged` class but stick to python's onboard `logging` module. If you want the logging from numpy-stl to behave any different, the best would be to use a separate logger instance (see also https://docs.python.org/2/library/logging.html#logger-objects).

**Comment by WoLpH** [comment]
It does use the Python onboard logging module actually :)

The `logger.Logged` class is simply a mixin which makes the Python logging module easily available using a logger specific to the class.

Essentially it makes sure you don't have to do something like this for every class:

```
import logging


logger = logging.getLogger(__name__)


class SomeClass(object):
    def __init__(self):
        self.logger = logger.getChild(self.__class__.__name__)

    def error(self, *args, **kwargs):
        self.logger.error(*args, **kwargs)

    ...
```

Which makes it easy to do `self.error('some message')`. Naturally you can repeat that for every class but it's a convenient mixin :)
