### ISSUE TITLE
debian / ubuntu packaging

### ISSUE THREAD

**Issue by arthurlutz** [WoLpH/numpy-stl#46]
It seems that numpy-stl is used by Cura https://github.com/Ultimaker/Cura/  Cura is distributed as a debian package for ubuntu/debian. 

It would be nice to have a debian package for numpy-stl tool that it could depend on or recommend.

**Comment by WoLpH** [comment]
Completely forgot to reply to this ticket, sorry about that.

While I think an Debian/Ubuntu package would be a great idea, I'm not entirely sure how to build one and too strapped for time to dive into that right now.

If someone has more expertise and is willing to create a pull request I'm all for that though.

**Comment by thopiekar** [comment]
Currently I started making packages for numpy-stl.

Is pytest-runner really essentially needed? https://github.com/WoLpH/numpy-stl/blob/master/setup.py#L64
It doesn't come with Ubuntu itself and thus I would need to package it, too.

**Comment by WoLpH** [comment]
Pytest runner is only required if you want to run tests from the `setup.py` file. If you use the `py.test` command manually the result is the same.

Additionally, the code is already tested through Travis anyhow so there is no real need to test.

**Comment by thopiekar** [comment]
Is it possible for you to make it optional? So I can pass an option and it will skip it?

This would be great! Thanks!

**Comment by WoLpH** [comment]
Sure, I've pushed a small update that should do the trick :)

Simply pass `--no-pytest-runner` to `setup.py` and it should do the trick.

**Comment by thopiekar** [comment]
I managed to pass --no-pytest-runner to be passed to the setup.py command, but the script says now that it is not recognized:
https://launchpadlibrarian.net/317672637/buildlog.txt.gz

**Comment by WoLpH** [comment]
Without overriding all used commands I don't think this will easily work. Perhaps we can switch to an environment variable instead?

Try this:
```
 PYTEST_RUNNER=false python2.7 setup.py clean
```

**Comment by WoLpH** [comment]
@thopiekar does the environment variable fix the issue?

**Comment by thopiekar** [comment]
Probably but it is not so trivial to set custom env variables in the packaging scripts. At least there they are not recognized.
Haven't had time to find a way to set it properly, sorry.

**Comment by WoLpH** [comment]
In that case, perhaps there is an existing environment variable we can use? 

Or are there any other options?
