### ISSUE TITLE
stl to nrrd volumes

### ISSUE THREAD

**Issue by sagarhukkire** [WoLpH/numpy-stl#49]
Hi 

I have mesh in .stl files and I want to convert to .nrrd files to get volume not header information.

How I can proceed? Thanks in advance

**Comment by WoLpH** [comment]
Honestly... I'm not familiar with the NRRD format at all so I'm not sure how to convert it.

**Comment by Uvar** [comment]
It is not possible to directly convert the unstructured .stl to .nrrd.

The way to go about this is to map first map the STL file back to a regular grid and then use this regular grid to obtain the volume segmentation required. 
http://www.scirun.org provides a tool which is able to do so.
Also, Slicer (https://www.slicer.org) might have something for this.

To develop from scratch, I'd suggest taking a look at vtkpython and existing solutions to convert between nrrd and dicom; as well as solutions to convert from dicom to stl (https://github.com/dave3d/dicom2stl). Perhaps the solution you are looking for can be reverse engineered.

**Comment by WoLpH** [comment]
Closing since this falls outside of the scope of this library
