### ISSUE TITLE
Normals per vertex

### ISSUE THREAD

**Issue by kjyv** [WoLpH/numpy-stl#51]
It would be nice to (optionally) get the normals for each vertex instead of per triangle. Usually adjacency information is needed for the triangles in that case, but I'm not sure there are any guarantees to the order of the triangles given in STL and therefore numpy-stl.

**Comment by WoLpH** [comment]
I think I might misunderstand the question but doesn't the `update_normals` method already do this?
https://github.com/WoLpH/numpy-stl/blob/develop/stl/base.py#L303-L305

It calculates the normals based on the vertices.

**Comment by kjyv** [comment]
No, it calculates the cross product of two vectors of the triangle v0,v1,v2, so the vector orthogonal to each face. The vector of a vertex is the normalized sum of the normals of the triangles that share that vertex. For rendering meshes, these normals are usually used for e.g. shading.

**Comment by kjyv** [comment]
I've since switched to trimesh for that purpose (and others), so maybe it can be considered out of scope for numpy-stl.

**Comment by WoLpH** [comment]
It's probably not that hard to implement but I'm quite strapped for time. 

Glad to see you were able to use trimesh, I actually looked at trimesh before I wrote this library but it was inconvenient for my case.

**Comment by WoLpH** [comment]
Oops... I think probot needs a bit of finetuning :)

**Comment by carterbox** [comment]
The `STL` format doesn't support storing per-vertex normals. It only allows one normal per face, so adding the ability for `numpy-stl` to calculate per vertex normals would be silly because once you saved your mesh, you would lose all of those normals.

**Comment by WoLpH** [comment]
It indeed seems a bit useless to have this method, if anyone needs it I'm open to pull requests though :)

**Comment by kjyv** [comment]
It's not at all useless if you want to open and render an stl file. If you don't consider this a use case for numpy-stl (which I think is fine), then there are alternatives as mentioned above.

**Comment by WoLpH** [comment]
That's a valid point. I'm not against pull requests though, but I'm not sure how the algorithm would look exactly. As far as I understand it requires normalizing the sum of the vertex normals but I'm fuzzy on the specifics.

Linear algebra is not my forte to be honest
