### ISSUE TITLE
Numpy-stl not installable under Windows 7 and Python 3

### ISSUE THREAD

**Issue by vollbier** [WoLpH/numpy-stl#54]
The numpy-stl package cannot be installed with Python 3 under Windows, since Cython does not
fully support Python 3. (At least v2.2.3 has this problem.) In the
"stl/_speedups.pyx" file the statement in line 4
``IF UNAME_SYSNAME == u"Windows":``
is not evaluated correctly.
Cheers, dietrich

PS: Tested on Window7, Python 3.6, Cython 0.25.2 (Anaconda 4.3)

**Comment by WoLpH** [comment]
Can you give the current develop branch a try? It should work even when the speedups module cannot be build correctly.

**Comment by vollbier** [comment]
That did the trick (Interestingly, I did not see any warning while installing).

**Comment by WoLpH** [comment]
Glad it worked.

The pure python version is more than fast enough in most cases and if you need more speed than I would recommend the binary stl files anyhow.

**Comment by Adammunich** [comment]
I found personally that creating a one line file:

#include <io.h>

Named unistd.h in ./stl/ solved the install issue for me.

**Comment by David-Herman** [comment]
I also wanted to report that I had a similar error under windows and Python 2.7.10 and the solution from @adammunich worked from me. Thanks. The numpy-stl package was v2.2.3  as well.

**Comment by WoLpH** [comment]
I finally had access to a windows machine with visual studio to test for myself and it seems that cython doesn't support python 3 on windows yet, or at least... not fully. The `UNAME_SYSNAME` constant isn't defined on windows it seems.
