### ISSUE TITLE
Translation by -COG doesn't make origo new COG

### ISSUE THREAD

**Issue by md2perpe** [WoLpH/numpy-stl#56]
After translating a mesh with -COG one would expect the new COG to be the coordinate origin (0, 0, 0) (modulo small float errors), but when running the code found in the gist with gear-complex.stl (also in the gist), the new COG is clearly off-origin. The z component changes from +1.6 to -12 and thus gets further away from origo.

https://gist.github.com/md2perpe/80b097e58ddfd5f6cb48c014875ab565

System info:
```
$ uname -srvmpio
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 unknown unknown GNU/Linux
```

**Comment by WoLpH** [comment]
I'v been looking at the COG code for a bit and what I can gather from the algorithm is that it's only approaching the COG but in most cases it will never reach it: https://www.geometrictools.com/Documentation/PolyhedralMassProperties.pdf

The code (or algorithm) wasn't written by me so I'm far from an expert on the matter unfortunately, a few tests locally indicated that running the algorithm a few times until a "stable" state has been reached functions slightly better.

Perhaps @uvar can provide some useful input?

**Comment by Uvar** [comment]
Well...

The short answer is: your intuition about -COG is right.
The semi-short answer: The STL file is quite badly corrupted and required repairs.
The long answer .. I haven't really gotten around to updating a bit of old code which auto-repaired meshes generated by 3D-scanners from Python 2 to Python 3 and re-ensuring compatibility with numpy-stl updates yet. Attached, please find the repaired file.

[Repaired.zip](https://github.com/WoLpH/numpy-stl/files/1128739/Repaired.zip)
Output from COG snippet you already typed @md2perpe : 
>>
```
COG: [ 28.0400547   -9.17302581   1.5331031 ]
COG: [  1.91787741e-06   3.48241772e-07  -3.53684678e-07]
```

For a valid STL object, the oriented area should sum up to zero within some floating arithmetic error.
```
    def area_or(self):
        v0 = self.data['vectors'][:, 0]
        v1 = self.data['vectors'][:, 1]
        v2 = self.data['vectors'][:, 2]
        
        normals = numpy.cross(v1 - v0, v2 - v0)
        #normals = self.normals
        #print normals1 == normals
        normals_sum = numpy.array([math.fsum(normals[:, 0]),
                                   math.fsum(normals[:, 1]),
                                   math.fsum(normals[:, 2])])
        return normals_sum
```
This same calculation of normals from the vertex ordering, underlies many packages and software programs dealing with stl-files. It is also mathematically the correct way of ordering vertices.
What I think happened with your file, as I did not see any visible corruption right away, and around 12k faces were deleted, is that there were a lot of unmatched faces somewhere inside the hull.

As a side note, @WoLpH I do not find it helpful to have the code tell me speedups failed without specifying the exception caught. There is something in the code sensitive to improperly specified STLs, as I didn't get a warning on the repaired STL.
