### ISSUE TITLE
Rotate and rotation-matrix

### ISSUE THREAD

**Issue by ipere** [WoLpH/numpy-stl#58]
Hello, 

I've read the documentation and the examples about the rotate method.
But I didn't understand if when you give a vector for the axis, your angle teta and a point it will do a rotation of teta around the axis which passes by the point and directed by the vector .

Or do I need to use rotation_matrix with my vector for the axis after translating all my points ? 

Thank you for your help

**Comment by WoLpH** [comment]
You understand correctly :)
The [`rotate`](http://numpy-stl.readthedocs.io/en/latest/stl.html?highlight=rotate#stl.Mesh.rotate) method automatically applies the needed translation operations if you pass a rotation point as you can see in the code here: https://github.com/WoLpH/numpy-stl/blob/a7a0f969ff5ddbae47c194146e0ee53dbdf33d3c/stl/base.py#L446-L452

The entire method:
```python

    def rotate(self, axis, theta, point=None):
        '''
        Rotate the matrix over the given axis by the given theta (angle)

        Uses the :py:func:`rotation_matrix` in the background.

        :param numpy.array axis: Axis to rotate over (x, y, z)
        :param float theta: Rotation angle in radians, use `math.radians` to
                            convert degrees to radians if needed.
        :param numpy.array point: Rotation point so manual translation is not
                                  required
        '''
        # No need to rotate if there is no actual rotation
        if not theta:
            return

        point = numpy.asarray(point or [0] * 3)
        rotation_matrix = self.rotation_matrix(axis, theta)

        # No need to rotate if there is no actual rotation
        if not rotation_matrix.any():
            return

        def _rotate(matrix):
            if point.any():
                # Translate while rotating
                return (matrix + point).dot(rotation_matrix) - point
            else:
                # Simply apply the rotation
                return matrix.dot(rotation_matrix)

        for i in range(3):
            self.vectors[:, i] = _rotate(self.vectors[:, i])
```

**Comment by ipere** [comment]
thank you :)

but I've got a problem.
I've got a point A = [-95, 97, 21] before my rotation, a vector N, and theta the angle in radians.
When I do your_mesh.rotate(N,theta,A) the point A became [52, 97, -211]

According to the method, there is no re-organization of the points after the rotation in your_mesh.
So, my point should not have moved as the rotation is around it ... 

I don't understand what happened.

**Comment by Uvar** [comment]
One thing is for sure: the point implementation is buggy. If you supply an array with 3 coordinates, an error is raised:
```
>>point
array([ -1.18494015e+01,  -4.39643860e-04,   5.91489744e+00], dtype=float32)

>>point = numpy.asarray(point or [0] * 3)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
If you make it a list though:

> >>point = [point[0], point[1], point[2]]
> >>bla = numpy.asarray(point or [0]*3)
> >>bla
> array([ -1.18494015e+01,  -4.39643860e-04,   5.91489744e+00], dtype=float32)

Apart from that we have the described failure mode.
```
>>(np.array([1,1,1]) + np.array([1,1,1])).dot(rot_mat) - np.array([1,1,1])
array([ 2.44109637, -1.34709779, -0.80409823])
```
Which is frankly quite silly, as this is to be expected. Instead of translating to the origin, rotating, and re-translating; the code first doubles the distance to the origin, then after rotating (which now does twice the translative displacement work in all dimensions, (R + R_point)*theta instead of R*theta), disfiguring the STL.

Luckily, we can easily solve this issue by setting 
```
def _rotate(matrix):
            if point.any():
                # Translate while rotating
                return (matrix - point).dot(rotation_matrix) + point
```
and the array problem by:
```
    if not len(point) == 3:
        point = [0]*3
    point = numpy.asarray(point)
```

**Comment by WoLpH** [comment]
Yes, the implementation is definitely broken in its current state. I'm wondering how I should fix it since it will break backwards compatibility...

**Comment by Uvar** [comment]
Fixing the rotation about a point to work as intended should not break any backwards compatibility, right?
As for the other issue..whoops

**Comment by WoLpH** [comment]
Well... it changes the current behaviour, even though it's wrong. Perhaps people have accounted for the wrong behaviour by inverting the point.

**Comment by WoLpH** [comment]
I've pushed a new release which fixes the broken rotation point, can you verify that things work as expected @ipere ?

**Comment by ipere** [comment]
Thank you ! 
Things are working correctly.

**Comment by WoLpH** [comment]
Glad to hear :)
