### ISSUE TITLE
Getting list of points without repetition

### ISSUE THREAD

**Issue by prapanchnair** [WoLpH/numpy-stl#61]
I see that there is no method to obtain the point cloud, i.e, all the vertices in the mesh without repetition. Currently I am doing this brute force, checking through all points. Is there an efficient way or am I missing a method?

**Comment by prapanchnair** [comment]
I found the solution. After getting all the vertices like so 

`all_points=numpy.row_stack((my_mesh.v0,my_mesh.v1,my_mesh.v2))`

use the unique function on the vertex tuples.

`unique_points=np.unique(all_points,axis=0)`

**Comment by WoLpH** [comment]
Good to hear :)
