### ISSUE TITLE
How can we smooth the 3D object ?

### ISSUE THREAD

**Issue by ybdesire** [WoLpH/numpy-stl#62]
Is it possible to do some pre-process as opencv to the 3D object?
Such as smooth ?

**Comment by WoLpH** [comment]
It's not impossible but that's quite complicated to do and far beyond the
scope of this project.

**Comment by ybdesire** [comment]
Thanks @WoLpH for the update. Do you have any idea to do this ?

**Comment by WoLpH** [comment]
It depends on the type of object but scipy has some methods available:
https://stackoverflow.com/questions/32753449/what-to-do-if-i-want-3d-spline-smooth-interpolation-of-random-unstructured-data

**Comment by ybdesire** [comment]
Thank you very much @WoLpH .   : )
