### ISSUE TITLE
How to generate STL from loaded numpy array?

### ISSUE THREAD

**Issue by ZibiGit** [WoLpH/numpy-stl#63]
Hello!

I'm struggling with a relatively simple issue. I've got several vtkPolyData files and I'd like to transform them into numpy arrays and then save them to npz file. For that purpose I decided to use numpy-stl module in such a way:

1. Convert vtkPolyData to STL files
2. Load STL files via numpy-stl
3. Save numpy arrays to npz file
4. Load npz file and get all arrays from them
5. Recreate STL files and then vtkPolyData files.

However, I do not know how to recreate the STL files from the loaded npz file. I would be grateful if you could help me. Here is a sample code for 2 stls in which I'm stuck (I don't know what to do next):

mesh_1 = mesh.Mesh.from_file("surface_1.stl")
mesh_2 = mesh.Mesh.from_file("surface_2.stl")
numpy.savez("file_with_arrays.npz",mesh_1=mesh_1,mesh_2 =mesh_2 )
new_mesh1=npzfile['mesh_1']
new_mesh1 = mesh.Mesh(new_mesh1, remove_empty_areas=False)
new_mesh1.normals
new_mesh1.save('new_stl_file1.stl')
new_mesh2=npzfile['mesh_2']
new_mesh2 = mesh.Mesh(new_mesh2, remove_empty_areas=False)
new_mesh2.normals
new_mesh2.save('new_stl_file2.stl')

This complicated way of trying to save vtkPolyData into numpy arrays seems strange, however, I don't know how I can do it without numpy-stl module. If you could propose another way of doing it, I'd be extremely grateful. I tried searching for transforming vtkPolyData into vtkArray, then into numpy array and then vice versa, but I didn't find anything helpful. Thank you in advance for your help!

**Comment by WoLpH** [comment]
I'm not that familiar with VTK so I can't really help you with that part.

But I can help with the rest of it :)
The `numy.savez` method is meant for numpy data and while dumping a `Mesh` object appears to succeed, it's actually losing information such as the `dtype`. So instead of using `savez` on `mesh_1` you should try `mesh_1.data` instead :) That's the raw numpy array that numpy-stl uses internally.

Example:
```
import numpy
from stl import mesh

mesh_1 = mesh.Mesh.from_file('surface_1.stl')

numpy.savez('file_with_arrays.npz', mesh_1=mesh_1.data)

npzfile = numpy.load('file_with_arrays.npz')

new_mesh_1 = mesh.Mesh(npzfile['mesh_1'], remove_empty_areas=False)

assert (new_mesh_1.data == mesh_1.data).all()
```

Do note that writing them to binary stl files is just as fast and slightly easier: `mesh_1.save('mesh_1.stl')`

**Comment by ZibiGit** [comment]
I'm extremely grateful for such a fast response. It works as intended! I have to save those files as npz files since I've got some more numpy arrays that have to be stored. Otherwise I'd just save those PolyData files as separate/merged STLs. I'm wondering whether _new_mesh.normals_ and _assert(new_mesh.data=mesh.data).all()_ are required for a successful conversion. What's purpose of those functions?

**Comment by WoLpH** [comment]
The `normals` is simply a shortcut to `data['normals']` so that statement does absolutely nothing: https://github.com/WoLpH/numpy-stl/blob/develop/stl/base.py#L194-L196

As for the `assert`, that's only to prove that `new_mesh_1.data` is equal to `mesh_1.data`. It's not needed for your code either.

**Comment by ZibiGit** [comment]
You have created a splendid package - I managed to save my entire case to a single npz file an reload it for further processing. Thank you for your time and help :)

**Comment by WoLpH** [comment]
Thank you :)

And you're welcome
