### ISSUE TITLE
Slicing with numpy-stl

### ISSUE THREAD

**Issue by darahan** [WoLpH/numpy-stl#66]
Hi,
Is there an option within numpy-stl to slice the 3D arrays in numpy into 2D slices? If not, do you have suggestions on how to do this?
Cheers and happy new year!

**Comment by WoLpH** [comment]
It's not that hard to do but it does require quite a bit of work. I would recommend to use a tool like Cura which has slicer code internally.

Internally Cura actually uses this library

**Comment by darahan** [comment]
I was just figuring if this was already in numpy-stl. I want to make my own machine specific slicer hence I will start to buid this on my own. Will have a good look at the cura code though.
Cheers
