### ISSUE TITLE
surface area for stl

### ISSUE THREAD

**Issue by vivek4890** [WoLpH/numpy-stl#77]
Hello,

I want to calculate surface area for stl file, is there any method I can use to get surface area like "get_mass_properties()", I used it to calculate volume. I'm new in Python please suggest how can I get the surface area for any .stl file.

thanks !

**Comment by Uvar** [comment]
This is not a numpy-stl issue, but basic calculus.

If I am correct, @WoLpH added a property to each polygon containing its area, which you can then just sum:
`myMesh.areas.sum()`

or calculate it by hand by doing a vector cross product

`        v0 = myMesh.data['vectors'][:, 0]
        v1 = myMesh.data['vectors'][:, 1]
        v2 = myMesh.data['vectors'][:, 2]

        normals = numpy.cross(v1 - v0, v2 - v0)`

**Comment by WoLpH** [comment]
Before `myMesh.areas` is available you'll need to call the `update_areas()` method. But after that it should work as @Uvar suggested :)

https://github.com/WoLpH/numpy-stl/blob/2cc27fc50f5f9f4e3dd8ed64e7f6d3c7ab00ef77/stl/base.py#L314-L316
