### ISSUE TITLE
help for stl-modification

### ISSUE THREAD

**Issue by plonkyy** [WoLpH/numpy-stl#8]
Hello, thanks for that great package!

but i still have problems to understand the structure. i want to open a stl from file, then search for points which have a z coordinate > 0, select these points and save the selected points as a new stl-file. 
how would you proceed? 

thanks!

**Comment by WoLpH** [comment]
Hi @plonkyy,

The documentation still needs some work for cases like these, but luckily since the last update (there was a similar question before #4) it's fairly easy now.

```python
import numpy
from stl.mesh import Mesh

stl_mesh = Mesh.from_file('input_file.stl')
non_zero_indices = numpy.any(stl_mesh.x > 0, axis=1)
data = stl_mesh.data[non_zero_indices]
new_mesh = Mesh(data)
new_mesh.save('output_file.stl')
```

Or a bit shorter:
```python
import numpy
from stl.mesh import Mesh

stl_mesh = Mesh.from_file('input_file.stl')
Mesh(stl_mesh.data[numpy.any(stl_mesh.x > 0, axis=1)]).save('output_file.stl')
```

**Comment by plonkyy** [comment]
Thank you so much! That helps me already a lot to understand the usage of your package.
On additional question:
what if i would like to skript a region growing algorithm with your pack? that means starting from a seed triangle i want to compare it´s normal vector with the one of a neighbor triangle. if the angle is < theta_crit I want to add the tringle to my region and so on. 

- how can i select the normal vector of a specific triangle?
- how can i store a triangle in a new data set, if it satisfies my criteria? 

In the moment I have not quite an idea how to start...Thank you already so much!

**Comment by WoLpH** [comment]
In the above example you can get the normal for triangle 100 with: `stl_mesh.normal[100]`, storing new triangles is a bit difficult as the library is written with performance in mind which makes adding/removing triangles a bit difficult.

The easiest is just to create a new mesh with a predefined amount of triangles (you can delete some later). Here's an example:
```python
from stl.mesh import Mesh

VERTICE_COUNT = 100
data = numpy.zeros(VERTICE_COUNT, dtype=Mesh.dtype)
mesh = Mesh(data, remove_empty_areas=False)

# To save to a STL file:
mesh.save('output_file.stl')
```

**Comment by plonkyy** [comment]
awesome! thanks, I figured out that. 
How would you suggest to surface plot an stl geometry using your data structure? 
Cheers 
plonkyy

**Comment by WoLpH** [comment]
Since there's no plotting capability in the library (or any helper
functions to make it easy), I would recommend trying matplotlib for that.

Here's a tutorial:
http://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html#surface-plots
In the case of the surface plot, all the required data should be in the
mesh already (i.e. `mesh.x` for the X values, `mesh.normals` for
facecolors). But they probably will need a little reshaping to work with
the `plot_surface` method.

**Comment by plonkyy** [comment]
cool thanks! i applied your module already successfully. but could you please explain me how your "data"-vector looks like? what values are stored in it? Thanks!

**Comment by WoLpH** [comment]
It uses the numpy dtype that's defined within the `Mesh` structure:

```python
data = numpy.zeros(VERTICE_COUNT, dtype=Mesh.dtype)
```

Here's what `Mesh.dtype` looks like:
```python
    dtype = numpy.dtype([
        ('normals', numpy.float32, (3, )),
        ('vectors', numpy.float32, (3, 3)),
        ('attr', numpy.uint16, (1, )),
    ])
```
The relevant documentation: http://numpy-stl.readthedocs.org/en/latest/stl.html#stl.base.BaseMesh.dtype

**Comment by plonkyy** [comment]
okay, I understood this, but I want to create a data array with a given set of vectors/normals.
I tried something like that:
data = numpy.array(stl_mesh.normals,stl_mesh.vectors, dtype=Mesh.dtype)
but was not successful. How does the line have to look?

**Comment by WoLpH** [comment]
You can't easily construct it in one line, while you can probably work around it using `numpy.vstack` or `numpy.hstack` I would not recommend it. Instead try this:

```python
data = numpy.zeros(stl_mesh.data.size, dtype=Mesh.dtype)
data.data['normals'] = stl_mesh.normals
data.data['vectors'] = stl_mesh.vectors
```

Or if you want to do it directly:
```python
data = numpy.zeros(stl_mesh.data.size, dtype=Mesh.dtype)
data.normals[:] = stl_mesh.normals
data.vectors[:] = stl_mesh.vectors
```

**Comment by plonkyy** [comment]
thank you! i tested that with following code:
~~~
import numpy
from stl.mesh import Mesh

stl_mesh = Mesh.from_file('BN2.stl')
data = numpy.zeros(stl_mesh.data.size, dtype=Mesh.dtype)
data.normals[:] = stl_mesh.normals
data.vectors[:] = stl_mesh.vectors
new_mesh = Mesh(data)
new_mesh.save('output.stl')
~~~
but I got the following error: 
AttributeError: 'numpy.ndarray' object has no attribute 'normals'
do you know what the problem is?

**Comment by WoLpH** [comment]
Oops... that's just my silly code. The `data` should be wrapped in a `Mesh()` object for it to work.

```python
import numpy
from stl.mesh import Mesh

stl_mesh = Mesh.from_file('BN2.stl')
data = numpy.zeros(stl_mesh.data.size, dtype=Mesh.dtype)
new_mesh = Mesh(data)
new_mesh.normals[:] = stl_mesh.normals
new_mesh.vectors[:] = stl_mesh.vectors
new_mesh.save('output.stl')
```

**Comment by plonkyy** [comment]
great thank you! : )

**Comment by vivek4890** [comment]
Hello Rick,

I want to calculate surface area for stl file, is there any method I can use to get surface area like "get_mass_properties()", I used it to calculate volume. I'm new in Python please suggest how can I get the surface area for any .stl file.

thanks !
