### ISSUE TITLE
`stl.mesh.Mesh.from_file` unable to obtain full mesh from stl file

### ISSUE THREAD

**Issue by joanneong** [WoLpH/numpy-stl#81]
**Operating System**
Linux, Ubuntu. Release 16.04

**Problem**
1. Attempt to load a mesh from an stl file using: 
`mesh = mesh.Mesh.from_file(r'./miljeep.stl')`

2. Do a print to check the number of triangles stored:
`print(mesh.vectors.shape)`

3. Realise that instead of getting the expected (53182, 3, 3), I am only getting (376, 3, 3).

Is this a bug with the `Mesh` package? What could be happening here?

P/S I am guessing that the stl file is fine because I can see it on https://3dviewer.net/

**Comment by WoLpH** [comment]
Can you attach the STL file (or link it) so I can see what's happening?

First guess... it's an STL file that contains multiple sub-stl files in which case you'll need the `from_multi_file` method: https://numpy-stl.readthedocs.io/en/latest/stl.html#stl.Mesh.from_multi_file

Examples: https://github.com/WoLpH/numpy-stl/blob/ba621131803ad94bcfdf24f8b26c3f92932f5c6d/tests/test_multiple.py#L17-L24

**Comment by joanneong** [comment]
@WoLpH Thanks for the prompt reply! The stl file is here: https://www.dropbox.com/s/9jjzg66ixuc3mjd/miljeep.stl?dl=0

Meanwhile, I will give what you've suggested a shot.

**Comment by joanneong** [comment]
@WoLpH Ah, it turns out that the stl file had some issue after all - numpy-stl is not at fault here :P 

Thanks for taking the time to look at this issue!
