### ISSUE TITLE
Cutting/Splitting .stl file

### ISSUE THREAD

**Issue by DavideBassano** [WoLpH/numpy-stl#85]
Hello, 
I have an .stl file with z-coordinates from 0 to ~200 (x and y don't matter) and I would like to cut it in z-direction in order to get a smaller one (e.g. with z-coordinates from 0 to 50). (Please see Image 1 - red line has nothing to do with it, it is used for another purpose)

Now I'm using NetFabb software (https://www.netfabb.com/blog/netfabb-basic-now-just-netfabb) and it works very well (Please see Image 2). Since I'm coding with Python and I'm using that "original" .stl file in my Python code, would be useful to have a code to cut this .stl and to generate a new .stl file from the original one, without using any external software.

Is there a way to do it with numpy-stl?

Thanks,
Cheers,

Davide Bassano

Image 1:
![99perc](https://user-images.githubusercontent.com/41295282/42992794-e4dd2b6a-8c09-11e8-9c7b-f811780f5d61.png)

Image 2:
![99perc5cm](https://user-images.githubusercontent.com/41295282/42992783-d77fa31c-8c09-11e8-821c-a716eb03845a.png)

**Comment by Uvar** [comment]
So if I understand correctly, you  want to make a cross-sectional cut at an arbitrary point?

I guess it can be done by:

1. Tracking which mesh faces intersect at the appropriate height
2. Interpolating points at this height to reduce said polygons to the appropriate dimensions
3. Enforcing new mesh points with arbitrary precision range of closeness to join (if Euclidean distance < cutoff, assume interpolation numerical artefact, they are supposed to be the same vertex)
4. Fill up the hole at z=cross-section height. This can for example be done by tracing the edges at this height, recursively adding a new polygon at the three subsequent vertices of the edge trace with the smallest angle between them. If you do not really care about the mesh quality in terms of aspect ratio, you can forgo this smallest angle requirement, just filling up as you encounter them.
Do take care to compare the normal of your prospective polygon to the unit vector [0,0,1], as with such a cut, it should definitely resemble this unit vector to numerical precision.

**Comment by DavideBassano** [comment]
Hi Uvar,

thank you very much for your reply.
I'll try what you are suggesting.

Thanks,
Cheers,

Davide
