### ISSUE TITLE
Combining STL files example

### ISSUE THREAD

**Issue by TheOncomingStorm** [WoLpH/numpy-stl#87]
Is there a purpose to the translate/rotate functions in the example for combining STL files? 

I'm trying to do something that should be rather simple but this example makes it incredibly confusing. I'm literally using the Modifying example to create several(like 2700) 3-sided "cubes" that I wrap around a cylinder but I need to combine them all once I'm done and the superfluous commands kinda muddy this up for me. 

I do have to give huge kudos though because it took me only an hour to get this far in creating this where most CAD programs have proven exceptionally difficult for something that I'd have considered incredibly simple back when I was doing 3D animations.

**Comment by WoLpH** [comment]
The purpose is to translate/rotate, but if you don't need those, don't use them :)
Most examples are pretty convoluted that way, they show a lot of optional mutations,

Effectively the combining of multiple stl files simply required you to put them in a single list. Nothing more :)

**Comment by TheOncomingStorm** [comment]
Awesome. Now I got it.

**Comment by LiangJinWei** [comment]
Excuse me, I want to ask how to control the position of the combined.stl.

For example,I want to put a  ball.stl  on the front edge of the  cube.stl , or put a triangle.stl on the top the cube.stl.

**Comment by LiangJinWei** [comment]
I got it!
Thank you so much!
