### ISSUE TITLE
Building a large stl

### ISSUE THREAD

**Issue by da4throux** [WoLpH/numpy-stl#97]
Hi,
Great module, really thanks a lot for that.
my script is building a large stl: doing an assembly of about 80k cubes for example.
I tested two approaches:
- building one big mesh, so that I can write a binary file: downside is that the script run slower and slower, because everything is in memory.
- building simple mesh in ASCII, and adding them as an stl in a multiple stl file at each iteration. The script does not slow down, it handles the load. But I end up with a huge file... >100Mb which is not best for the rest of the pipeline

I was wondering if there is a third approach with the best of both world ?

**Comment by WoLpH** [comment]
It's possible but I'm not sure if it will cause any problems. The binary stl format starts with a header that specifies the amount of vertices. After that it's plain binary writing of the data.

Still though, 80k cubes is not an insane amount and numpy stores it in memory really efficiently. I would not expect too many problems with memory usage.

**Comment by WoLpH** [comment]
Thinking about it slightly further, it shouldn't be too hard to write a binary stl merge script. That would allow you to write a bunch of binary stl files and merge them after. 

I'll give it a shot once I have time (probably within a week)

**Comment by WoLpH** [comment]
I've created a simple method to merge both ascii and binary files. It does (at max) take twice the amount of memory it would normally take. That can be worked around but it's a tradeoff between reading the files multiple times and using a bit more memory temporarily. Please let me know if it's enough or not :)

My best guess for the size of a 80k cubes wouldn't be that bad though. A single triangle takes 50 bytes. A side of a cube would be 2 triangles, so 100 bytes. There are 6 sides to a cube so 100 * 6 * 80k would be about 45.8 MiB. Hardly a stellar amount :)
Max memory usage would be around 100 MiB for this operation.
